// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package sidecarv1

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_QueryRandomnessRequest       protoreflect.MessageDescriptor
	fd_QueryRandomnessRequest_round protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_sidecar_v1_vrf_proto_init()
	md_QueryRandomnessRequest = File_vexxvakan_sidecar_v1_vrf_proto.Messages().ByName("QueryRandomnessRequest")
	fd_QueryRandomnessRequest_round = md_QueryRandomnessRequest.Fields().ByName("round")
}

var _ protoreflect.Message = (*fastReflection_QueryRandomnessRequest)(nil)

type fastReflection_QueryRandomnessRequest QueryRandomnessRequest

func (x *QueryRandomnessRequest) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryRandomnessRequest)(x)
}

func (x *QueryRandomnessRequest) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryRandomnessRequest_messageType fastReflection_QueryRandomnessRequest_messageType
var _ protoreflect.MessageType = fastReflection_QueryRandomnessRequest_messageType{}

type fastReflection_QueryRandomnessRequest_messageType struct{}

func (x fastReflection_QueryRandomnessRequest_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryRandomnessRequest)(nil)
}
func (x fastReflection_QueryRandomnessRequest_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryRandomnessRequest)
}
func (x fastReflection_QueryRandomnessRequest_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryRandomnessRequest
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryRandomnessRequest) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryRandomnessRequest
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryRandomnessRequest) Type() protoreflect.MessageType {
	return _fastReflection_QueryRandomnessRequest_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryRandomnessRequest) New() protoreflect.Message {
	return new(fastReflection_QueryRandomnessRequest)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryRandomnessRequest) Interface() protoreflect.ProtoMessage {
	return (*QueryRandomnessRequest)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryRandomnessRequest) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Round != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Round)
		if !f(fd_QueryRandomnessRequest_round, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryRandomnessRequest) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessRequest.round":
		return x.Round != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessRequest does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryRandomnessRequest) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessRequest.round":
		x.Round = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessRequest does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryRandomnessRequest) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessRequest.round":
		value := x.Round
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessRequest does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryRandomnessRequest) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessRequest.round":
		x.Round = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessRequest does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryRandomnessRequest) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessRequest.round":
		panic(fmt.Errorf("field round of message vexxvakan.sidecar.v1.QueryRandomnessRequest is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessRequest does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryRandomnessRequest) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessRequest.round":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessRequest does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryRandomnessRequest) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.sidecar.v1.QueryRandomnessRequest", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryRandomnessRequest) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryRandomnessRequest) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryRandomnessRequest) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryRandomnessRequest) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryRandomnessRequest)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Round != 0 {
			n += 1 + runtime.Sov(uint64(x.Round))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryRandomnessRequest)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.Round != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Round))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryRandomnessRequest)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryRandomnessRequest: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryRandomnessRequest: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
				}
				x.Round = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Round |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_QueryRandomnessResponse                    protoreflect.MessageDescriptor
	fd_QueryRandomnessResponse_drand_round        protoreflect.FieldDescriptor
	fd_QueryRandomnessResponse_randomness         protoreflect.FieldDescriptor
	fd_QueryRandomnessResponse_signature          protoreflect.FieldDescriptor
	fd_QueryRandomnessResponse_previous_signature protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_sidecar_v1_vrf_proto_init()
	md_QueryRandomnessResponse = File_vexxvakan_sidecar_v1_vrf_proto.Messages().ByName("QueryRandomnessResponse")
	fd_QueryRandomnessResponse_drand_round = md_QueryRandomnessResponse.Fields().ByName("drand_round")
	fd_QueryRandomnessResponse_randomness = md_QueryRandomnessResponse.Fields().ByName("randomness")
	fd_QueryRandomnessResponse_signature = md_QueryRandomnessResponse.Fields().ByName("signature")
	fd_QueryRandomnessResponse_previous_signature = md_QueryRandomnessResponse.Fields().ByName("previous_signature")
}

var _ protoreflect.Message = (*fastReflection_QueryRandomnessResponse)(nil)

type fastReflection_QueryRandomnessResponse QueryRandomnessResponse

func (x *QueryRandomnessResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryRandomnessResponse)(x)
}

func (x *QueryRandomnessResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryRandomnessResponse_messageType fastReflection_QueryRandomnessResponse_messageType
var _ protoreflect.MessageType = fastReflection_QueryRandomnessResponse_messageType{}

type fastReflection_QueryRandomnessResponse_messageType struct{}

func (x fastReflection_QueryRandomnessResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryRandomnessResponse)(nil)
}
func (x fastReflection_QueryRandomnessResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryRandomnessResponse)
}
func (x fastReflection_QueryRandomnessResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryRandomnessResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryRandomnessResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryRandomnessResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryRandomnessResponse) Type() protoreflect.MessageType {
	return _fastReflection_QueryRandomnessResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryRandomnessResponse) New() protoreflect.Message {
	return new(fastReflection_QueryRandomnessResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryRandomnessResponse) Interface() protoreflect.ProtoMessage {
	return (*QueryRandomnessResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryRandomnessResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.DrandRound != uint64(0) {
		value := protoreflect.ValueOfUint64(x.DrandRound)
		if !f(fd_QueryRandomnessResponse_drand_round, value) {
			return
		}
	}
	if len(x.Randomness) != 0 {
		value := protoreflect.ValueOfBytes(x.Randomness)
		if !f(fd_QueryRandomnessResponse_randomness, value) {
			return
		}
	}
	if len(x.Signature) != 0 {
		value := protoreflect.ValueOfBytes(x.Signature)
		if !f(fd_QueryRandomnessResponse_signature, value) {
			return
		}
	}
	if len(x.PreviousSignature) != 0 {
		value := protoreflect.ValueOfBytes(x.PreviousSignature)
		if !f(fd_QueryRandomnessResponse_previous_signature, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryRandomnessResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.drand_round":
		return x.DrandRound != uint64(0)
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.randomness":
		return len(x.Randomness) != 0
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.signature":
		return len(x.Signature) != 0
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.previous_signature":
		return len(x.PreviousSignature) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryRandomnessResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.drand_round":
		x.DrandRound = uint64(0)
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.randomness":
		x.Randomness = nil
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.signature":
		x.Signature = nil
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.previous_signature":
		x.PreviousSignature = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryRandomnessResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.drand_round":
		value := x.DrandRound
		return protoreflect.ValueOfUint64(value)
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.randomness":
		value := x.Randomness
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.signature":
		value := x.Signature
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.previous_signature":
		value := x.PreviousSignature
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryRandomnessResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.drand_round":
		x.DrandRound = value.Uint()
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.randomness":
		x.Randomness = value.Bytes()
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.signature":
		x.Signature = value.Bytes()
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.previous_signature":
		x.PreviousSignature = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryRandomnessResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.drand_round":
		panic(fmt.Errorf("field drand_round of message vexxvakan.sidecar.v1.QueryRandomnessResponse is not mutable"))
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.randomness":
		panic(fmt.Errorf("field randomness of message vexxvakan.sidecar.v1.QueryRandomnessResponse is not mutable"))
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.signature":
		panic(fmt.Errorf("field signature of message vexxvakan.sidecar.v1.QueryRandomnessResponse is not mutable"))
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.previous_signature":
		panic(fmt.Errorf("field previous_signature of message vexxvakan.sidecar.v1.QueryRandomnessResponse is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryRandomnessResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.drand_round":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.randomness":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.signature":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.sidecar.v1.QueryRandomnessResponse.previous_signature":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryRandomnessResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryRandomnessResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryRandomnessResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.sidecar.v1.QueryRandomnessResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryRandomnessResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryRandomnessResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryRandomnessResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryRandomnessResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryRandomnessResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.DrandRound != 0 {
			n += 1 + runtime.Sov(uint64(x.DrandRound))
		}
		l = len(x.Randomness)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Signature)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PreviousSignature)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryRandomnessResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.PreviousSignature) > 0 {
			i -= len(x.PreviousSignature)
			copy(dAtA[i:], x.PreviousSignature)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PreviousSignature)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Signature) > 0 {
			i -= len(x.Signature)
			copy(dAtA[i:], x.Signature)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Signature)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Randomness) > 0 {
			i -= len(x.Randomness)
			copy(dAtA[i:], x.Randomness)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Randomness)))
			i--
			dAtA[i] = 0x12
		}
		if x.DrandRound != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.DrandRound))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryRandomnessResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryRandomnessResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryRandomnessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DrandRound", wireType)
				}
				x.DrandRound = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.DrandRound |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Randomness", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Randomness = append(x.Randomness[:0], dAtA[iNdEx:postIndex]...)
				if x.Randomness == nil {
					x.Randomness = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Signature = append(x.Signature[:0], dAtA[iNdEx:postIndex]...)
				if x.Signature == nil {
					x.Signature = []byte{}
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PreviousSignature", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PreviousSignature = append(x.PreviousSignature[:0], dAtA[iNdEx:postIndex]...)
				if x.PreviousSignature == nil {
					x.PreviousSignature = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_QueryInfoRequest protoreflect.MessageDescriptor
)

func init() {
	file_vexxvakan_sidecar_v1_vrf_proto_init()
	md_QueryInfoRequest = File_vexxvakan_sidecar_v1_vrf_proto.Messages().ByName("QueryInfoRequest")
}

var _ protoreflect.Message = (*fastReflection_QueryInfoRequest)(nil)

type fastReflection_QueryInfoRequest QueryInfoRequest

func (x *QueryInfoRequest) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryInfoRequest)(x)
}

func (x *QueryInfoRequest) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryInfoRequest_messageType fastReflection_QueryInfoRequest_messageType
var _ protoreflect.MessageType = fastReflection_QueryInfoRequest_messageType{}

type fastReflection_QueryInfoRequest_messageType struct{}

func (x fastReflection_QueryInfoRequest_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryInfoRequest)(nil)
}
func (x fastReflection_QueryInfoRequest_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryInfoRequest)
}
func (x fastReflection_QueryInfoRequest_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryInfoRequest
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryInfoRequest) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryInfoRequest
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryInfoRequest) Type() protoreflect.MessageType {
	return _fastReflection_QueryInfoRequest_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryInfoRequest) New() protoreflect.Message {
	return new(fastReflection_QueryInfoRequest)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryInfoRequest) Interface() protoreflect.ProtoMessage {
	return (*QueryInfoRequest)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryInfoRequest) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryInfoRequest) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoRequest does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryInfoRequest) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoRequest does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryInfoRequest) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoRequest does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryInfoRequest) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoRequest does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryInfoRequest) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoRequest does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryInfoRequest) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoRequest"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoRequest does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryInfoRequest) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.sidecar.v1.QueryInfoRequest", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryInfoRequest) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryInfoRequest) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryInfoRequest) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryInfoRequest) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryInfoRequest)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryInfoRequest)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryInfoRequest)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryInfoRequest: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_QueryInfoResponse                  protoreflect.MessageDescriptor
	fd_QueryInfoResponse_chain_hash       protoreflect.FieldDescriptor
	fd_QueryInfoResponse_public_key       protoreflect.FieldDescriptor
	fd_QueryInfoResponse_period_seconds   protoreflect.FieldDescriptor
	fd_QueryInfoResponse_genesis_unix_sec protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_sidecar_v1_vrf_proto_init()
	md_QueryInfoResponse = File_vexxvakan_sidecar_v1_vrf_proto.Messages().ByName("QueryInfoResponse")
	fd_QueryInfoResponse_chain_hash = md_QueryInfoResponse.Fields().ByName("chain_hash")
	fd_QueryInfoResponse_public_key = md_QueryInfoResponse.Fields().ByName("public_key")
	fd_QueryInfoResponse_period_seconds = md_QueryInfoResponse.Fields().ByName("period_seconds")
	fd_QueryInfoResponse_genesis_unix_sec = md_QueryInfoResponse.Fields().ByName("genesis_unix_sec")
}

var _ protoreflect.Message = (*fastReflection_QueryInfoResponse)(nil)

type fastReflection_QueryInfoResponse QueryInfoResponse

func (x *QueryInfoResponse) ProtoReflect() protoreflect.Message {
	return (*fastReflection_QueryInfoResponse)(x)
}

func (x *QueryInfoResponse) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_QueryInfoResponse_messageType fastReflection_QueryInfoResponse_messageType
var _ protoreflect.MessageType = fastReflection_QueryInfoResponse_messageType{}

type fastReflection_QueryInfoResponse_messageType struct{}

func (x fastReflection_QueryInfoResponse_messageType) Zero() protoreflect.Message {
	return (*fastReflection_QueryInfoResponse)(nil)
}
func (x fastReflection_QueryInfoResponse_messageType) New() protoreflect.Message {
	return new(fastReflection_QueryInfoResponse)
}
func (x fastReflection_QueryInfoResponse_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryInfoResponse
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_QueryInfoResponse) Descriptor() protoreflect.MessageDescriptor {
	return md_QueryInfoResponse
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_QueryInfoResponse) Type() protoreflect.MessageType {
	return _fastReflection_QueryInfoResponse_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_QueryInfoResponse) New() protoreflect.Message {
	return new(fastReflection_QueryInfoResponse)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_QueryInfoResponse) Interface() protoreflect.ProtoMessage {
	return (*QueryInfoResponse)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_QueryInfoResponse) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if len(x.ChainHash) != 0 {
		value := protoreflect.ValueOfBytes(x.ChainHash)
		if !f(fd_QueryInfoResponse_chain_hash, value) {
			return
		}
	}
	if len(x.PublicKey) != 0 {
		value := protoreflect.ValueOfBytes(x.PublicKey)
		if !f(fd_QueryInfoResponse_public_key, value) {
			return
		}
	}
	if x.PeriodSeconds != uint64(0) {
		value := protoreflect.ValueOfUint64(x.PeriodSeconds)
		if !f(fd_QueryInfoResponse_period_seconds, value) {
			return
		}
	}
	if x.GenesisUnixSec != int64(0) {
		value := protoreflect.ValueOfInt64(x.GenesisUnixSec)
		if !f(fd_QueryInfoResponse_genesis_unix_sec, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_QueryInfoResponse) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryInfoResponse.chain_hash":
		return len(x.ChainHash) != 0
	case "vexxvakan.sidecar.v1.QueryInfoResponse.public_key":
		return len(x.PublicKey) != 0
	case "vexxvakan.sidecar.v1.QueryInfoResponse.period_seconds":
		return x.PeriodSeconds != uint64(0)
	case "vexxvakan.sidecar.v1.QueryInfoResponse.genesis_unix_sec":
		return x.GenesisUnixSec != int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoResponse does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryInfoResponse) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryInfoResponse.chain_hash":
		x.ChainHash = nil
	case "vexxvakan.sidecar.v1.QueryInfoResponse.public_key":
		x.PublicKey = nil
	case "vexxvakan.sidecar.v1.QueryInfoResponse.period_seconds":
		x.PeriodSeconds = uint64(0)
	case "vexxvakan.sidecar.v1.QueryInfoResponse.genesis_unix_sec":
		x.GenesisUnixSec = int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoResponse does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_QueryInfoResponse) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.sidecar.v1.QueryInfoResponse.chain_hash":
		value := x.ChainHash
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.sidecar.v1.QueryInfoResponse.public_key":
		value := x.PublicKey
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.sidecar.v1.QueryInfoResponse.period_seconds":
		value := x.PeriodSeconds
		return protoreflect.ValueOfUint64(value)
	case "vexxvakan.sidecar.v1.QueryInfoResponse.genesis_unix_sec":
		value := x.GenesisUnixSec
		return protoreflect.ValueOfInt64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoResponse does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryInfoResponse) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryInfoResponse.chain_hash":
		x.ChainHash = value.Bytes()
	case "vexxvakan.sidecar.v1.QueryInfoResponse.public_key":
		x.PublicKey = value.Bytes()
	case "vexxvakan.sidecar.v1.QueryInfoResponse.period_seconds":
		x.PeriodSeconds = value.Uint()
	case "vexxvakan.sidecar.v1.QueryInfoResponse.genesis_unix_sec":
		x.GenesisUnixSec = value.Int()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoResponse does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryInfoResponse) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryInfoResponse.chain_hash":
		panic(fmt.Errorf("field chain_hash of message vexxvakan.sidecar.v1.QueryInfoResponse is not mutable"))
	case "vexxvakan.sidecar.v1.QueryInfoResponse.public_key":
		panic(fmt.Errorf("field public_key of message vexxvakan.sidecar.v1.QueryInfoResponse is not mutable"))
	case "vexxvakan.sidecar.v1.QueryInfoResponse.period_seconds":
		panic(fmt.Errorf("field period_seconds of message vexxvakan.sidecar.v1.QueryInfoResponse is not mutable"))
	case "vexxvakan.sidecar.v1.QueryInfoResponse.genesis_unix_sec":
		panic(fmt.Errorf("field genesis_unix_sec of message vexxvakan.sidecar.v1.QueryInfoResponse is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoResponse does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_QueryInfoResponse) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.sidecar.v1.QueryInfoResponse.chain_hash":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.sidecar.v1.QueryInfoResponse.public_key":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.sidecar.v1.QueryInfoResponse.period_seconds":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vexxvakan.sidecar.v1.QueryInfoResponse.genesis_unix_sec":
		return protoreflect.ValueOfInt64(int64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.sidecar.v1.QueryInfoResponse"))
		}
		panic(fmt.Errorf("message vexxvakan.sidecar.v1.QueryInfoResponse does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_QueryInfoResponse) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.sidecar.v1.QueryInfoResponse", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_QueryInfoResponse) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_QueryInfoResponse) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_QueryInfoResponse) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_QueryInfoResponse) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*QueryInfoResponse)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.ChainHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PublicKey)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.PeriodSeconds != 0 {
			n += 1 + runtime.Sov(uint64(x.PeriodSeconds))
		}
		if x.GenesisUnixSec != 0 {
			n += 1 + runtime.Sov(uint64(x.GenesisUnixSec))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*QueryInfoResponse)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.GenesisUnixSec != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.GenesisUnixSec))
			i--
			dAtA[i] = 0x20
		}
		if x.PeriodSeconds != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.PeriodSeconds))
			i--
			dAtA[i] = 0x18
		}
		if len(x.PublicKey) > 0 {
			i -= len(x.PublicKey)
			copy(dAtA[i:], x.PublicKey)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PublicKey)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.ChainHash) > 0 {
			i -= len(x.ChainHash)
			copy(dAtA[i:], x.ChainHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ChainHash)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*QueryInfoResponse)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryInfoResponse: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: QueryInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ChainHash", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ChainHash = append(x.ChainHash[:0], dAtA[iNdEx:postIndex]...)
				if x.ChainHash == nil {
					x.ChainHash = []byte{}
				}
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PublicKey = append(x.PublicKey[:0], dAtA[iNdEx:postIndex]...)
				if x.PublicKey == nil {
					x.PublicKey = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PeriodSeconds", wireType)
				}
				x.PeriodSeconds = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.PeriodSeconds |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field GenesisUnixSec", wireType)
				}
				x.GenesisUnixSec = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.GenesisUnixSec |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: vexxvakan/sidecar/v1/vrf.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryRandomnessRequest defines the request type for the Randomness method.
// A round of zero indicates that the caller is requesting the latest beacon.
type QueryRandomnessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Round uint64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
}

func (x *QueryRandomnessRequest) Reset() {
	*x = QueryRandomnessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRandomnessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRandomnessRequest) ProtoMessage() {}

// Deprecated: Use QueryRandomnessRequest.ProtoReflect.Descriptor instead.
func (*QueryRandomnessRequest) Descriptor() ([]byte, []int) {
	return file_vexxvakan_sidecar_v1_vrf_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRandomnessRequest) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

// QueryRandomnessResponse carries a single drand beacon.
type QueryRandomnessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// drand_round is the drand round number.
	DrandRound uint64 `protobuf:"varint,1,opt,name=drand_round,json=drandRound,proto3" json:"drand_round,omitempty"`
	// randomness is SHA256(signature).
	Randomness []byte `protobuf:"bytes,2,opt,name=randomness,proto3" json:"randomness,omitempty"`
	// signature is the drand BLS signature for this round.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// previous_signature is the BLS signature of the previous round, required
	// for chained-scheme verification.
	PreviousSignature []byte `protobuf:"bytes,4,opt,name=previous_signature,json=previousSignature,proto3" json:"previous_signature,omitempty"`
}

func (x *QueryRandomnessResponse) Reset() {
	*x = QueryRandomnessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryRandomnessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRandomnessResponse) ProtoMessage() {}

// Deprecated: Use QueryRandomnessResponse.ProtoReflect.Descriptor instead.
func (*QueryRandomnessResponse) Descriptor() ([]byte, []int) {
	return file_vexxvakan_sidecar_v1_vrf_proto_rawDescGZIP(), []int{1}
}

func (x *QueryRandomnessResponse) GetDrandRound() uint64 {
	if x != nil {
		return x.DrandRound
	}
	return 0
}

func (x *QueryRandomnessResponse) GetRandomness() []byte {
	if x != nil {
		return x.Randomness
	}
	return nil
}

func (x *QueryRandomnessResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *QueryRandomnessResponse) GetPreviousSignature() []byte {
	if x != nil {
		return x.PreviousSignature
	}
	return nil
}

// QueryInfoRequest defines the request type for the Info method.
type QueryInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *QueryInfoRequest) Reset() {
	*x = QueryInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInfoRequest) ProtoMessage() {}

// Deprecated: Use QueryInfoRequest.ProtoReflect.Descriptor instead.
func (*QueryInfoRequest) Descriptor() ([]byte, []int) {
	return file_vexxvakan_sidecar_v1_vrf_proto_rawDescGZIP(), []int{2}
}

// QueryInfoResponse carries static drand chain information.
type QueryInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// chain_hash is the canonical identifier for the drand chain.
	ChainHash []byte `protobuf:"bytes,1,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
	// public_key is the collective BLS public key for the drand group.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// period_seconds is the drand beacon period in seconds.
	PeriodSeconds uint64 `protobuf:"varint,3,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// genesis_unix_sec is the drand genesis time (UNIX seconds) for round 1.
	GenesisUnixSec int64 `protobuf:"varint,4,opt,name=genesis_unix_sec,json=genesisUnixSec,proto3" json:"genesis_unix_sec,omitempty"`
}

func (x *QueryInfoResponse) Reset() {
	*x = QueryInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInfoResponse) ProtoMessage() {}

// Deprecated: Use QueryInfoResponse.ProtoReflect.Descriptor instead.
func (*QueryInfoResponse) Descriptor() ([]byte, []int) {
	return file_vexxvakan_sidecar_v1_vrf_proto_rawDescGZIP(), []int{3}
}

func (x *QueryInfoResponse) GetChainHash() []byte {
	if x != nil {
		return x.ChainHash
	}
	return nil
}

func (x *QueryInfoResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *QueryInfoResponse) GetPeriodSeconds() uint64 {
	if x != nil {
		return x.PeriodSeconds
	}
	return 0
}

func (x *QueryInfoResponse) GetGenesisUnixSec() int64 {
	if x != nil {
		return x.GenesisUnixSec
	}
	return 0
}

var File_vexxvakan_sidecar_v1_vrf_proto protoreflect.FileDescriptor

var file_vexxvakan_sidecar_v1_vrf_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x73, 0x69, 0x64, 0x65,
	0x63, 0x61, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x72, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x73, 0x69, 0x64, 0x65,
	0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x16, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x22, 0xa7, 0x01, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61,
	0x6e, 0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x64, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e,
	0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x2d, 0x0a, 0x12, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x12,
	0x0a, 0x10, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xa2, 0x01, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64,
	0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x28, 0x0a,
	0x10, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x73, 0x65,
	0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x67, 0x65, 0x6e, 0x65, 0x73, 0x69, 0x73,
	0x55, 0x6e, 0x69, 0x78, 0x53, 0x65, 0x63, 0x32, 0xfc, 0x01, 0x0a, 0x03, 0x56, 0x72, 0x66, 0x12,
	0x85, 0x01, 0x0a, 0x0a, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x2c,
	0x2e, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63,
	0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x64, 0x6f,
	0x6d, 0x6e, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x76,
	0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x6e,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x6d, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x26, 0x2e, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x73, 0x69, 0x64, 0x65,
	0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61,
	0x6b, 0x61, 0x6e, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x12, 0x0c, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x76,
	0x31, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0xc7, 0x01, 0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x2e, 0x76,
	0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72,
	0x2e, 0x76, 0x31, 0x42, 0x08, 0x56, 0x72, 0x66, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x73, 0x69, 0x64, 0x65,
	0x63, 0x61, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x56, 0x53, 0x58, 0xaa, 0x02, 0x14, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b,
	0x61, 0x6e, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x14,
	0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x5c, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61,
	0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x20, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e,
	0x5c, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x16, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61,
	0x6b, 0x61, 0x6e, 0x3a, 0x3a, 0x53, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x3a, 0x3a, 0x56, 0x31,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vexxvakan_sidecar_v1_vrf_proto_rawDescOnce sync.Once
	file_vexxvakan_sidecar_v1_vrf_proto_rawDescData = file_vexxvakan_sidecar_v1_vrf_proto_rawDesc
)

func file_vexxvakan_sidecar_v1_vrf_proto_rawDescGZIP() []byte {
	file_vexxvakan_sidecar_v1_vrf_proto_rawDescOnce.Do(func() {
		file_vexxvakan_sidecar_v1_vrf_proto_rawDescData = protoimpl.X.CompressGZIP(file_vexxvakan_sidecar_v1_vrf_proto_rawDescData)
	})
	return file_vexxvakan_sidecar_v1_vrf_proto_rawDescData
}

var file_vexxvakan_sidecar_v1_vrf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vexxvakan_sidecar_v1_vrf_proto_goTypes = []interface{}{
	(*QueryRandomnessRequest)(nil),  // 0: vexxvakan.sidecar.v1.QueryRandomnessRequest
	(*QueryRandomnessResponse)(nil), // 1: vexxvakan.sidecar.v1.QueryRandomnessResponse
	(*QueryInfoRequest)(nil),        // 2: vexxvakan.sidecar.v1.QueryInfoRequest
	(*QueryInfoResponse)(nil),       // 3: vexxvakan.sidecar.v1.QueryInfoResponse
}
var file_vexxvakan_sidecar_v1_vrf_proto_depIdxs = []int32{
	0, // 0: vexxvakan.sidecar.v1.Vrf.Randomness:input_type -> vexxvakan.sidecar.v1.QueryRandomnessRequest
	2, // 1: vexxvakan.sidecar.v1.Vrf.Info:input_type -> vexxvakan.sidecar.v1.QueryInfoRequest
	1, // 2: vexxvakan.sidecar.v1.Vrf.Randomness:output_type -> vexxvakan.sidecar.v1.QueryRandomnessResponse
	3, // 3: vexxvakan.sidecar.v1.Vrf.Info:output_type -> vexxvakan.sidecar.v1.QueryInfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vexxvakan_sidecar_v1_vrf_proto_init() }
func file_vexxvakan_sidecar_v1_vrf_proto_init() {
	if File_vexxvakan_sidecar_v1_vrf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRandomnessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryRandomnessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vexxvakan_sidecar_v1_vrf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vexxvakan_sidecar_v1_vrf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vexxvakan_sidecar_v1_vrf_proto_goTypes,
		DependencyIndexes: file_vexxvakan_sidecar_v1_vrf_proto_depIdxs,
		MessageInfos:      file_vexxvakan_sidecar_v1_vrf_proto_msgTypes,
	}.Build()
	File_vexxvakan_sidecar_v1_vrf_proto = out.File
	file_vexxvakan_sidecar_v1_vrf_proto_rawDesc = nil
	file_vexxvakan_sidecar_v1_vrf_proto_goTypes = nil
	file_vexxvakan_sidecar_v1_vrf_proto_depIdxs = nil
}
