// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: vexxvakan/sidecar/v1/vrf.proto

package sidecarv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Vrf_Randomness_FullMethodName = "/vexxvakan.sidecar.v1.Vrf/Randomness"
	Vrf_Info_FullMethodName       = "/vexxvakan.sidecar.v1.Vrf/Info"
)

// VrfClient is the client API for Vrf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Vrf defines the gRPC VRF sidecar service.
type VrfClient interface {
	// Randomness returns a drand beacon for a specific round or the latest
	// available beacon when round is unset (zero).
	Randomness(ctx context.Context, in *QueryRandomnessRequest, opts ...grpc.CallOption) (*QueryRandomnessResponse, error)
	// Info returns static drand chain information used for verification and
	// debugging.
	Info(ctx context.Context, in *QueryInfoRequest, opts ...grpc.CallOption) (*QueryInfoResponse, error)
}

type vrfClient struct {
	cc grpc.ClientConnInterface
}

func NewVrfClient(cc grpc.ClientConnInterface) VrfClient {
	return &vrfClient{cc}
}

func (c *vrfClient) Randomness(ctx context.Context, in *QueryRandomnessRequest, opts ...grpc.CallOption) (*QueryRandomnessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryRandomnessResponse)
	err := c.cc.Invoke(ctx, Vrf_Randomness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vrfClient) Info(ctx context.Context, in *QueryInfoRequest, opts ...grpc.CallOption) (*QueryInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryInfoResponse)
	err := c.cc.Invoke(ctx, Vrf_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VrfServer is the server API for Vrf service.
// All implementations must embed UnimplementedVrfServer
// for forward compatibility.
//
// Vrf defines the gRPC VRF sidecar service.
type VrfServer interface {
	// Randomness returns a drand beacon for a specific round or the latest
	// available beacon when round is unset (zero).
	Randomness(context.Context, *QueryRandomnessRequest) (*QueryRandomnessResponse, error)
	// Info returns static drand chain information used for verification and
	// debugging.
	Info(context.Context, *QueryInfoRequest) (*QueryInfoResponse, error)
	mustEmbedUnimplementedVrfServer()
}

// UnimplementedVrfServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVrfServer struct{}

func (UnimplementedVrfServer) Randomness(context.Context, *QueryRandomnessRequest) (*QueryRandomnessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Randomness not implemented")
}
func (UnimplementedVrfServer) Info(context.Context, *QueryInfoRequest) (*QueryInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedVrfServer) mustEmbedUnimplementedVrfServer() {}
func (UnimplementedVrfServer) testEmbeddedByValue()             {}

// UnsafeVrfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VrfServer will
// result in compilation errors.
type UnsafeVrfServer interface {
	mustEmbedUnimplementedVrfServer()
}

func RegisterVrfServer(s grpc.ServiceRegistrar, srv VrfServer) {
	// If the following call panics, it indicates UnimplementedVrfServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Vrf_ServiceDesc, srv)
}

func _Vrf_Randomness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRandomnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VrfServer).Randomness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vrf_Randomness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VrfServer).Randomness(ctx, req.(*QueryRandomnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vrf_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VrfServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Vrf_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VrfServer).Info(ctx, req.(*QueryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Vrf_ServiceDesc is the grpc.ServiceDesc for Vrf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Vrf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vexxvakan.sidecar.v1.Vrf",
	HandlerType: (*VrfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Randomness",
			Handler:    _Vrf_Randomness_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Vrf_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vexxvakan/sidecar/v1/vrf.proto",
}
