// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vexxvakan/sidecar/v1/vrf.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryRandomnessRequest defines the request type for the Randomness method.
// A round of zero indicates that the caller is requesting the latest beacon.
type QueryRandomnessRequest struct {
	Round uint64 `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
}

func (m *QueryRandomnessRequest) Reset()         { *m = QueryRandomnessRequest{} }
func (m *QueryRandomnessRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRandomnessRequest) ProtoMessage()    {}
func (*QueryRandomnessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e17d5d50cdf00b3d, []int{0}
}
func (m *QueryRandomnessRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomnessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomnessRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomnessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomnessRequest.Merge(m, src)
}
func (m *QueryRandomnessRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomnessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomnessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomnessRequest proto.InternalMessageInfo

func (m *QueryRandomnessRequest) GetRound() uint64 {
	if m != nil {
		return m.Round
	}
	return 0
}

// QueryRandomnessResponse carries a single drand beacon.
type QueryRandomnessResponse struct {
	// drand_round is the drand round number.
	DrandRound uint64 `protobuf:"varint,1,opt,name=drand_round,json=drandRound,proto3" json:"drand_round,omitempty"`
	// randomness is SHA256(signature).
	Randomness []byte `protobuf:"bytes,2,opt,name=randomness,proto3" json:"randomness,omitempty"`
	// signature is the drand BLS signature for this round.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// previous_signature is the BLS signature of the previous round, required
	// for chained-scheme verification.
	PreviousSignature []byte `protobuf:"bytes,4,opt,name=previous_signature,json=previousSignature,proto3" json:"previous_signature,omitempty"`
}

func (m *QueryRandomnessResponse) Reset()         { *m = QueryRandomnessResponse{} }
func (m *QueryRandomnessResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRandomnessResponse) ProtoMessage()    {}
func (*QueryRandomnessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e17d5d50cdf00b3d, []int{1}
}
func (m *QueryRandomnessResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomnessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomnessResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomnessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomnessResponse.Merge(m, src)
}
func (m *QueryRandomnessResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomnessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomnessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomnessResponse proto.InternalMessageInfo

func (m *QueryRandomnessResponse) GetDrandRound() uint64 {
	if m != nil {
		return m.DrandRound
	}
	return 0
}

func (m *QueryRandomnessResponse) GetRandomness() []byte {
	if m != nil {
		return m.Randomness
	}
	return nil
}

func (m *QueryRandomnessResponse) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *QueryRandomnessResponse) GetPreviousSignature() []byte {
	if m != nil {
		return m.PreviousSignature
	}
	return nil
}

// QueryInfoRequest defines the request type for the Info method.
type QueryInfoRequest struct {
}

func (m *QueryInfoRequest) Reset()         { *m = QueryInfoRequest{} }
func (m *QueryInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInfoRequest) ProtoMessage()    {}
func (*QueryInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e17d5d50cdf00b3d, []int{2}
}
func (m *QueryInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoRequest.Merge(m, src)
}
func (m *QueryInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoRequest proto.InternalMessageInfo

// QueryInfoResponse carries static drand chain information.
type QueryInfoResponse struct {
	// chain_hash is the canonical identifier for the drand chain.
	ChainHash []byte `protobuf:"bytes,1,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
	// public_key is the collective BLS public key for the drand group.
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// period_seconds is the drand beacon period in seconds.
	PeriodSeconds uint64 `protobuf:"varint,3,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// genesis_unix_sec is the drand genesis time (UNIX seconds) for round 1.
	GenesisUnixSec int64 `protobuf:"varint,4,opt,name=genesis_unix_sec,json=genesisUnixSec,proto3" json:"genesis_unix_sec,omitempty"`
}

func (m *QueryInfoResponse) Reset()         { *m = QueryInfoResponse{} }
func (m *QueryInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInfoResponse) ProtoMessage()    {}
func (*QueryInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e17d5d50cdf00b3d, []int{3}
}
func (m *QueryInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInfoResponse.Merge(m, src)
}
func (m *QueryInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInfoResponse proto.InternalMessageInfo

func (m *QueryInfoResponse) GetChainHash() []byte {
	if m != nil {
		return m.ChainHash
	}
	return nil
}

func (m *QueryInfoResponse) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *QueryInfoResponse) GetPeriodSeconds() uint64 {
	if m != nil {
		return m.PeriodSeconds
	}
	return 0
}

func (m *QueryInfoResponse) GetGenesisUnixSec() int64 {
	if m != nil {
		return m.GenesisUnixSec
	}
	return 0
}

func init() {
	proto.RegisterType((*QueryRandomnessRequest)(nil), "vexxvakan.sidecar.v1.QueryRandomnessRequest")
	proto.RegisterType((*QueryRandomnessResponse)(nil), "vexxvakan.sidecar.v1.QueryRandomnessResponse")
	proto.RegisterType((*QueryInfoRequest)(nil), "vexxvakan.sidecar.v1.QueryInfoRequest")
	proto.RegisterType((*QueryInfoResponse)(nil), "vexxvakan.sidecar.v1.QueryInfoResponse")
}

func init() { proto.RegisterFile("vexxvakan/sidecar/v1/vrf.proto", fileDescriptor_e17d5d50cdf00b3d) }

var fileDescriptor_e17d5d50cdf00b3d = []byte{
	// 468 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xbb, 0x4d, 0x40, 0xca, 0x10, 0xa2, 0x76, 0x15, 0x41, 0x14, 0x15, 0x53, 0x59, 0x02,
	0x72, 0xa0, 0xb6, 0x5a, 0xde, 0x80, 0x13, 0x08, 0x2e, 0x38, 0x82, 0x03, 0x17, 0x6b, 0x63, 0x4f,
	0xec, 0x55, 0x9b, 0x5d, 0xb3, 0x63, 0x5b, 0xc9, 0x15, 0x89, 0x3b, 0x12, 0x6f, 0xc0, 0x85, 0x57,
	0xe1, 0x58, 0x89, 0x0b, 0x47, 0x94, 0xf0, 0x18, 0x1c, 0x90, 0xd7, 0x4e, 0x63, 0x89, 0x0a, 0x38,
	0xe6, 0xfb, 0xe7, 0xcf, 0xfc, 0x9e, 0x99, 0x05, 0xa7, 0xc4, 0xe5, 0xb2, 0x14, 0xe7, 0x42, 0xf9,
	0x24, 0x63, 0x8c, 0x84, 0xf1, 0xcb, 0x53, 0xbf, 0x34, 0x73, 0x2f, 0x33, 0x3a, 0xd7, 0x7c, 0x78,
	0xa5, 0x7b, 0x8d, 0xee, 0x95, 0xa7, 0xe3, 0xa3, 0x44, 0xeb, 0xe4, 0x02, 0x7d, 0x91, 0x49, 0x5f,
	0x28, 0xa5, 0x73, 0x91, 0x4b, 0xad, 0xa8, 0xf6, 0xb8, 0x1e, 0xdc, 0x79, 0x55, 0xa0, 0x59, 0x05,
	0x42, 0xc5, 0x7a, 0xa1, 0x90, 0x28, 0xc0, 0x77, 0x05, 0x52, 0xce, 0x87, 0x70, 0xc3, 0xe8, 0x42,
	0xc5, 0x23, 0x76, 0xcc, 0x26, 0xdd, 0xa0, 0xfe, 0xe1, 0x7e, 0x61, 0x70, 0xf7, 0x0f, 0x03, 0x65,
	0x5a, 0x11, 0xf2, 0xfb, 0x70, 0x2b, 0x36, 0x42, 0xc5, 0x61, 0xdb, 0x07, 0x16, 0x05, 0x15, 0xe1,
	0x0e, 0x80, 0xb9, 0xb2, 0x8d, 0xf6, 0x8f, 0xd9, 0xa4, 0x1f, 0xb4, 0x08, 0x3f, 0x82, 0x1e, 0xc9,
	0x44, 0x89, 0xbc, 0x30, 0x38, 0xea, 0x58, 0x79, 0x07, 0xf8, 0x09, 0xf0, 0xcc, 0x60, 0x29, 0x75,
	0x41, 0xe1, 0xae, 0xac, 0x6b, 0xcb, 0x0e, 0xb7, 0xca, 0x74, 0x2b, 0xb8, 0x1c, 0x0e, 0x6c, 0xd0,
	0xe7, 0x6a, 0xae, 0x9b, 0x6f, 0x72, 0x3f, 0x33, 0x38, 0x6c, 0xc1, 0x26, 0xf7, 0x3d, 0x80, 0x28,
	0x15, 0x52, 0x85, 0xa9, 0xa0, 0xd4, 0xc6, 0xee, 0x07, 0x3d, 0x4b, 0x9e, 0x09, 0x4a, 0x2b, 0x39,
	0x2b, 0x66, 0x17, 0x32, 0x0a, 0xcf, 0x71, 0xd5, 0xa4, 0xee, 0xd5, 0xe4, 0x05, 0xae, 0xf8, 0x03,
	0x18, 0x64, 0x68, 0xa4, 0x8e, 0x43, 0xc2, 0x48, 0xab, 0x98, 0x6c, 0xf2, 0x6e, 0x70, 0xbb, 0xa6,
	0xd3, 0x1a, 0xf2, 0x09, 0x1c, 0x24, 0xa8, 0x90, 0x24, 0x85, 0x85, 0x92, 0xcb, 0xaa, 0xd8, 0x66,
	0xef, 0x04, 0x83, 0x86, 0xbf, 0x56, 0x72, 0x39, 0xc5, 0xe8, 0xec, 0x17, 0x83, 0xce, 0x1b, 0x33,
	0xe7, 0x1f, 0x18, 0xc0, 0x6e, 0xca, 0xfc, 0xb1, 0x77, 0xdd, 0x7a, 0xbd, 0xeb, 0xb7, 0x37, 0x3e,
	0xf9, 0xcf, 0xea, 0x7a, 0x04, 0xee, 0xf8, 0xfd, 0xb7, 0x9f, 0x9f, 0xf6, 0x87, 0x9c, 0x57, 0xe7,
	0x54, 0x5d, 0x55, 0x6b, 0x2b, 0x0b, 0xe8, 0x56, 0xe3, 0xe2, 0x0f, 0xff, 0xf2, 0x97, 0xad, 0x21,
	0x8f, 0x1f, 0xfd, 0xb3, 0xae, 0x69, 0x3a, 0xb4, 0x4d, 0x07, 0xbc, 0xbf, 0x6d, 0x2a, 0xd5, 0x5c,
	0x3f, 0x7d, 0xf9, 0x75, 0xed, 0xb0, 0xcb, 0xb5, 0xc3, 0x7e, 0xac, 0x1d, 0xf6, 0x71, 0xe3, 0xec,
	0x5d, 0x6e, 0x9c, 0xbd, 0xef, 0x1b, 0x67, 0xef, 0xed, 0x59, 0x22, 0xf3, 0xb4, 0x98, 0x79, 0x91,
	0x5e, 0xf8, 0xbb, 0xa7, 0x50, 0x79, 0xb7, 0xcf, 0x81, 0xd0, 0x94, 0x68, 0xc8, 0xb2, 0x7c, 0x95,
	0x21, 0xcd, 0x6e, 0xda, 0x33, 0x7f, 0xf2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x0b, 0x06, 0x32,
	0x3c, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VrfClient is the client API for Vrf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VrfClient interface {
	// Randomness returns a drand beacon for a specific round or the latest
	// available beacon when round is unset (zero).
	Randomness(ctx context.Context, in *QueryRandomnessRequest, opts ...grpc.CallOption) (*QueryRandomnessResponse, error)
	// Info returns static drand chain information used for verification and
	// debugging.
	Info(ctx context.Context, in *QueryInfoRequest, opts ...grpc.CallOption) (*QueryInfoResponse, error)
}

type vrfClient struct {
	cc grpc1.ClientConn
}

func NewVrfClient(cc grpc1.ClientConn) VrfClient {
	return &vrfClient{cc}
}

func (c *vrfClient) Randomness(ctx context.Context, in *QueryRandomnessRequest, opts ...grpc.CallOption) (*QueryRandomnessResponse, error) {
	out := new(QueryRandomnessResponse)
	err := c.cc.Invoke(ctx, "/vexxvakan.sidecar.v1.Vrf/Randomness", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vrfClient) Info(ctx context.Context, in *QueryInfoRequest, opts ...grpc.CallOption) (*QueryInfoResponse, error) {
	out := new(QueryInfoResponse)
	err := c.cc.Invoke(ctx, "/vexxvakan.sidecar.v1.Vrf/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VrfServer is the server API for Vrf service.
type VrfServer interface {
	// Randomness returns a drand beacon for a specific round or the latest
	// available beacon when round is unset (zero).
	Randomness(context.Context, *QueryRandomnessRequest) (*QueryRandomnessResponse, error)
	// Info returns static drand chain information used for verification and
	// debugging.
	Info(context.Context, *QueryInfoRequest) (*QueryInfoResponse, error)
}

// UnimplementedVrfServer can be embedded to have forward compatible implementations.
type UnimplementedVrfServer struct {
}

func (*UnimplementedVrfServer) Randomness(ctx context.Context, req *QueryRandomnessRequest) (*QueryRandomnessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Randomness not implemented")
}
func (*UnimplementedVrfServer) Info(ctx context.Context, req *QueryInfoRequest) (*QueryInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Info not implemented")
}

func RegisterVrfServer(s grpc1.Server, srv VrfServer) {
	s.RegisterService(&_Vrf_serviceDesc, srv)
}

func _Vrf_Randomness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRandomnessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VrfServer).Randomness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vexxvakan.sidecar.v1.Vrf/Randomness",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VrfServer).Randomness(ctx, req.(*QueryRandomnessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vrf_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VrfServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vexxvakan.sidecar.v1.Vrf/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VrfServer).Info(ctx, req.(*QueryInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Vrf_serviceDesc = _Vrf_serviceDesc
var _Vrf_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vexxvakan.sidecar.v1.Vrf",
	HandlerType: (*VrfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Randomness",
			Handler:    _Vrf_Randomness_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Vrf_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vexxvakan/sidecar/v1/vrf.proto",
}

func (m *QueryRandomnessRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomnessRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomnessRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Round != 0 {
		i = encodeVarintVrf(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRandomnessResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomnessResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomnessResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PreviousSignature) > 0 {
		i -= len(m.PreviousSignature)
		copy(dAtA[i:], m.PreviousSignature)
		i = encodeVarintVrf(dAtA, i, uint64(len(m.PreviousSignature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintVrf(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Randomness) > 0 {
		i -= len(m.Randomness)
		copy(dAtA[i:], m.Randomness)
		i = encodeVarintVrf(dAtA, i, uint64(len(m.Randomness)))
		i--
		dAtA[i] = 0x12
	}
	if m.DrandRound != 0 {
		i = encodeVarintVrf(dAtA, i, uint64(m.DrandRound))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GenesisUnixSec != 0 {
		i = encodeVarintVrf(dAtA, i, uint64(m.GenesisUnixSec))
		i--
		dAtA[i] = 0x20
	}
	if m.PeriodSeconds != 0 {
		i = encodeVarintVrf(dAtA, i, uint64(m.PeriodSeconds))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintVrf(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ChainHash) > 0 {
		i -= len(m.ChainHash)
		copy(dAtA[i:], m.ChainHash)
		i = encodeVarintVrf(dAtA, i, uint64(len(m.ChainHash)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVrf(dAtA []byte, offset int, v uint64) int {
	offset -= sovVrf(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryRandomnessRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Round != 0 {
		n += 1 + sovVrf(uint64(m.Round))
	}
	return n
}

func (m *QueryRandomnessResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DrandRound != 0 {
		n += 1 + sovVrf(uint64(m.DrandRound))
	}
	l = len(m.Randomness)
	if l > 0 {
		n += 1 + l + sovVrf(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovVrf(uint64(l))
	}
	l = len(m.PreviousSignature)
	if l > 0 {
		n += 1 + l + sovVrf(uint64(l))
	}
	return n
}

func (m *QueryInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainHash)
	if l > 0 {
		n += 1 + l + sovVrf(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovVrf(uint64(l))
	}
	if m.PeriodSeconds != 0 {
		n += 1 + sovVrf(uint64(m.PeriodSeconds))
	}
	if m.GenesisUnixSec != 0 {
		n += 1 + sovVrf(uint64(m.GenesisUnixSec))
	}
	return n
}

func sovVrf(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVrf(x uint64) (n int) {
	return sovVrf(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryRandomnessRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVrf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomnessRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomnessRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVrf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVrf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRandomnessResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVrf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomnessResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomnessResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandRound", wireType)
			}
			m.DrandRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DrandRound |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Randomness", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Randomness = append(m.Randomness[:0], dAtA[iNdEx:postIndex]...)
			if m.Randomness == nil {
				m.Randomness = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousSignature = append(m.PreviousSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.PreviousSignature == nil {
				m.PreviousSignature = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVrf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVrf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVrf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipVrf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVrf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVrf
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainHash = append(m.ChainHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ChainHash == nil {
				m.ChainHash = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVrf
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVrf
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodSeconds", wireType)
			}
			m.PeriodSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisUnixSec", wireType)
			}
			m.GenesisUnixSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenesisUnixSec |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVrf(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVrf
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVrf(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVrf
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVrf
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVrf
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVrf
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVrf
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVrf        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVrf          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVrf = fmt.Errorf("proto: unexpected end of group")
)
