// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package abciv1

import (
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_VrfVoteExtension                    protoreflect.MessageDescriptor
	fd_VrfVoteExtension_drand_round        protoreflect.FieldDescriptor
	fd_VrfVoteExtension_randomness         protoreflect.FieldDescriptor
	fd_VrfVoteExtension_signature          protoreflect.FieldDescriptor
	fd_VrfVoteExtension_previous_signature protoreflect.FieldDescriptor
	fd_VrfVoteExtension_chain_hash         protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_vrf_abci_v1_vote_extension_proto_init()
	md_VrfVoteExtension = File_vexxvakan_vrf_abci_v1_vote_extension_proto.Messages().ByName("VrfVoteExtension")
	fd_VrfVoteExtension_drand_round = md_VrfVoteExtension.Fields().ByName("drand_round")
	fd_VrfVoteExtension_randomness = md_VrfVoteExtension.Fields().ByName("randomness")
	fd_VrfVoteExtension_signature = md_VrfVoteExtension.Fields().ByName("signature")
	fd_VrfVoteExtension_previous_signature = md_VrfVoteExtension.Fields().ByName("previous_signature")
	fd_VrfVoteExtension_chain_hash = md_VrfVoteExtension.Fields().ByName("chain_hash")
}

var _ protoreflect.Message = (*fastReflection_VrfVoteExtension)(nil)

type fastReflection_VrfVoteExtension VrfVoteExtension

func (x *VrfVoteExtension) ProtoReflect() protoreflect.Message {
	return (*fastReflection_VrfVoteExtension)(x)
}

func (x *VrfVoteExtension) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_vrf_abci_v1_vote_extension_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_VrfVoteExtension_messageType fastReflection_VrfVoteExtension_messageType
var _ protoreflect.MessageType = fastReflection_VrfVoteExtension_messageType{}

type fastReflection_VrfVoteExtension_messageType struct{}

func (x fastReflection_VrfVoteExtension_messageType) Zero() protoreflect.Message {
	return (*fastReflection_VrfVoteExtension)(nil)
}
func (x fastReflection_VrfVoteExtension_messageType) New() protoreflect.Message {
	return new(fastReflection_VrfVoteExtension)
}
func (x fastReflection_VrfVoteExtension_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfVoteExtension
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_VrfVoteExtension) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfVoteExtension
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_VrfVoteExtension) Type() protoreflect.MessageType {
	return _fastReflection_VrfVoteExtension_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_VrfVoteExtension) New() protoreflect.Message {
	return new(fastReflection_VrfVoteExtension)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_VrfVoteExtension) Interface() protoreflect.ProtoMessage {
	return (*VrfVoteExtension)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_VrfVoteExtension) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.DrandRound != uint64(0) {
		value := protoreflect.ValueOfUint64(x.DrandRound)
		if !f(fd_VrfVoteExtension_drand_round, value) {
			return
		}
	}
	if len(x.Randomness) != 0 {
		value := protoreflect.ValueOfBytes(x.Randomness)
		if !f(fd_VrfVoteExtension_randomness, value) {
			return
		}
	}
	if len(x.Signature) != 0 {
		value := protoreflect.ValueOfBytes(x.Signature)
		if !f(fd_VrfVoteExtension_signature, value) {
			return
		}
	}
	if len(x.PreviousSignature) != 0 {
		value := protoreflect.ValueOfBytes(x.PreviousSignature)
		if !f(fd_VrfVoteExtension_previous_signature, value) {
			return
		}
	}
	if len(x.ChainHash) != 0 {
		value := protoreflect.ValueOfBytes(x.ChainHash)
		if !f(fd_VrfVoteExtension_chain_hash, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_VrfVoteExtension) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.drand_round":
		return x.DrandRound != uint64(0)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.randomness":
		return len(x.Randomness) != 0
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.signature":
		return len(x.Signature) != 0
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.previous_signature":
		return len(x.PreviousSignature) != 0
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.chain_hash":
		return len(x.ChainHash) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.abci.v1.VrfVoteExtension"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.abci.v1.VrfVoteExtension does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfVoteExtension) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.drand_round":
		x.DrandRound = uint64(0)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.randomness":
		x.Randomness = nil
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.signature":
		x.Signature = nil
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.previous_signature":
		x.PreviousSignature = nil
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.chain_hash":
		x.ChainHash = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.abci.v1.VrfVoteExtension"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.abci.v1.VrfVoteExtension does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_VrfVoteExtension) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.drand_round":
		value := x.DrandRound
		return protoreflect.ValueOfUint64(value)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.randomness":
		value := x.Randomness
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.signature":
		value := x.Signature
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.previous_signature":
		value := x.PreviousSignature
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.chain_hash":
		value := x.ChainHash
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.abci.v1.VrfVoteExtension"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.abci.v1.VrfVoteExtension does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfVoteExtension) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.drand_round":
		x.DrandRound = value.Uint()
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.randomness":
		x.Randomness = value.Bytes()
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.signature":
		x.Signature = value.Bytes()
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.previous_signature":
		x.PreviousSignature = value.Bytes()
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.chain_hash":
		x.ChainHash = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.abci.v1.VrfVoteExtension"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.abci.v1.VrfVoteExtension does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfVoteExtension) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.drand_round":
		panic(fmt.Errorf("field drand_round of message vexxvakan.vrf.abci.v1.VrfVoteExtension is not mutable"))
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.randomness":
		panic(fmt.Errorf("field randomness of message vexxvakan.vrf.abci.v1.VrfVoteExtension is not mutable"))
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.signature":
		panic(fmt.Errorf("field signature of message vexxvakan.vrf.abci.v1.VrfVoteExtension is not mutable"))
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.previous_signature":
		panic(fmt.Errorf("field previous_signature of message vexxvakan.vrf.abci.v1.VrfVoteExtension is not mutable"))
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.chain_hash":
		panic(fmt.Errorf("field chain_hash of message vexxvakan.vrf.abci.v1.VrfVoteExtension is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.abci.v1.VrfVoteExtension"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.abci.v1.VrfVoteExtension does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_VrfVoteExtension) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.drand_round":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.randomness":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.signature":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.previous_signature":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.abci.v1.VrfVoteExtension.chain_hash":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.abci.v1.VrfVoteExtension"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.abci.v1.VrfVoteExtension does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_VrfVoteExtension) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.vrf.abci.v1.VrfVoteExtension", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_VrfVoteExtension) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfVoteExtension) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_VrfVoteExtension) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_VrfVoteExtension) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*VrfVoteExtension)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.DrandRound != 0 {
			n += 1 + runtime.Sov(uint64(x.DrandRound))
		}
		l = len(x.Randomness)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Signature)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PreviousSignature)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ChainHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*VrfVoteExtension)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.ChainHash) > 0 {
			i -= len(x.ChainHash)
			copy(dAtA[i:], x.ChainHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ChainHash)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.PreviousSignature) > 0 {
			i -= len(x.PreviousSignature)
			copy(dAtA[i:], x.PreviousSignature)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PreviousSignature)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Signature) > 0 {
			i -= len(x.Signature)
			copy(dAtA[i:], x.Signature)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Signature)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Randomness) > 0 {
			i -= len(x.Randomness)
			copy(dAtA[i:], x.Randomness)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Randomness)))
			i--
			dAtA[i] = 0x12
		}
		if x.DrandRound != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.DrandRound))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*VrfVoteExtension)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfVoteExtension: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfVoteExtension: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DrandRound", wireType)
				}
				x.DrandRound = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.DrandRound |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Randomness", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Randomness = append(x.Randomness[:0], dAtA[iNdEx:postIndex]...)
				if x.Randomness == nil {
					x.Randomness = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Signature = append(x.Signature[:0], dAtA[iNdEx:postIndex]...)
				if x.Signature == nil {
					x.Signature = []byte{}
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PreviousSignature", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PreviousSignature = append(x.PreviousSignature[:0], dAtA[iNdEx:postIndex]...)
				if x.PreviousSignature == nil {
					x.PreviousSignature = []byte{}
				}
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ChainHash", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ChainHash = append(x.ChainHash[:0], dAtA[iNdEx:postIndex]...)
				if x.ChainHash == nil {
					x.ChainHash = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: vexxvakan/vrf/abci/v1/vote_extension.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VrfVoteExtension carries a single drand beacon for a specific round.
type VrfVoteExtension struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DrandRound        uint64 `protobuf:"varint,1,opt,name=drand_round,json=drandRound,proto3" json:"drand_round,omitempty"`
	Randomness        []byte `protobuf:"bytes,2,opt,name=randomness,proto3" json:"randomness,omitempty"`
	Signature         []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PreviousSignature []byte `protobuf:"bytes,4,opt,name=previous_signature,json=previousSignature,proto3" json:"previous_signature,omitempty"`
	ChainHash         []byte `protobuf:"bytes,5,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
}

func (x *VrfVoteExtension) Reset() {
	*x = VrfVoteExtension{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_vrf_abci_v1_vote_extension_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfVoteExtension) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfVoteExtension) ProtoMessage() {}

// Deprecated: Use VrfVoteExtension.ProtoReflect.Descriptor instead.
func (*VrfVoteExtension) Descriptor() ([]byte, []int) {
	return file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDescGZIP(), []int{0}
}

func (x *VrfVoteExtension) GetDrandRound() uint64 {
	if x != nil {
		return x.DrandRound
	}
	return 0
}

func (x *VrfVoteExtension) GetRandomness() []byte {
	if x != nil {
		return x.Randomness
	}
	return nil
}

func (x *VrfVoteExtension) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VrfVoteExtension) GetPreviousSignature() []byte {
	if x != nil {
		return x.PreviousSignature
	}
	return nil
}

func (x *VrfVoteExtension) GetChainHash() []byte {
	if x != nil {
		return x.ChainHash
	}
	return nil
}

var File_vexxvakan_vrf_abci_v1_vote_extension_proto protoreflect.FileDescriptor

var file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x76, 0x72, 0x66, 0x2f,
	0x61, 0x62, 0x63, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x78, 0x74,
	0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x76, 0x65,
	0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e, 0x61, 0x62, 0x63, 0x69,
	0x2e, 0x76, 0x31, 0x22, 0xbf, 0x01, 0x0a, 0x10, 0x56, 0x72, 0x66, 0x56, 0x6f, 0x74, 0x65, 0x45,
	0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x72, 0x61, 0x6e,
	0x64, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x64,
	0x72, 0x61, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x61, 0x6e,
	0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x72,
	0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x70, 0x72, 0x65, 0x76, 0x69,
	0x6f, 0x75, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x11, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x48, 0x61, 0x73, 0x68, 0x42, 0xd5, 0x01, 0x0a, 0x19, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65,
	0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e, 0x61, 0x62, 0x63, 0x69,
	0x2e, 0x76, 0x31, 0x42, 0x12, 0x56, 0x6f, 0x74, 0x65, 0x45, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2d, 0x63, 0x6f, 0x73, 0x6d, 0x6f,
	0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x65, 0x78, 0x78,
	0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x61, 0x62, 0x63, 0x69, 0x2f, 0x76,
	0x31, 0x3b, 0x61, 0x62, 0x63, 0x69, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x56, 0x56, 0x41, 0xaa, 0x02,
	0x15, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x56, 0x72, 0x66, 0x2e, 0x41,
	0x62, 0x63, 0x69, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x15, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b,
	0x61, 0x6e, 0x5c, 0x56, 0x72, 0x66, 0x5c, 0x41, 0x62, 0x63, 0x69, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x21, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x5c, 0x56, 0x72, 0x66, 0x5c, 0x41,
	0x62, 0x63, 0x69, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0xea, 0x02, 0x18, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x3a, 0x3a,
	0x56, 0x72, 0x66, 0x3a, 0x3a, 0x41, 0x62, 0x63, 0x69, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDescOnce sync.Once
	file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDescData = file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDesc
)

func file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDescGZIP() []byte {
	file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDescOnce.Do(func() {
		file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDescData = protoimpl.X.CompressGZIP(file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDescData)
	})
	return file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDescData
}

var file_vexxvakan_vrf_abci_v1_vote_extension_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vexxvakan_vrf_abci_v1_vote_extension_proto_goTypes = []interface{}{
	(*VrfVoteExtension)(nil), // 0: vexxvakan.vrf.abci.v1.VrfVoteExtension
}
var file_vexxvakan_vrf_abci_v1_vote_extension_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vexxvakan_vrf_abci_v1_vote_extension_proto_init() }
func file_vexxvakan_vrf_abci_v1_vote_extension_proto_init() {
	if File_vexxvakan_vrf_abci_v1_vote_extension_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vexxvakan_vrf_abci_v1_vote_extension_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfVoteExtension); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vexxvakan_vrf_abci_v1_vote_extension_proto_goTypes,
		DependencyIndexes: file_vexxvakan_vrf_abci_v1_vote_extension_proto_depIdxs,
		MessageInfos:      file_vexxvakan_vrf_abci_v1_vote_extension_proto_msgTypes,
	}.Build()
	File_vexxvakan_vrf_abci_v1_vote_extension_proto = out.File
	file_vexxvakan_vrf_abci_v1_vote_extension_proto_rawDesc = nil
	file_vexxvakan_vrf_abci_v1_vote_extension_proto_goTypes = nil
	file_vexxvakan_vrf_abci_v1_vote_extension_proto_depIdxs = nil
}
