// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vexxvakan/vrf/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest requests the current VRF parameters.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0eafac98a734a97, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse carries the current VRF parameters. The fields mirror
// x/vrf's VrfParams type; the module keeper converts between the two.
type QueryParamsResponse struct {
	Params VrfParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0eafac98a734a97, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() VrfParams {
	if m != nil {
		return m.Params
	}
	return VrfParams{}
}

// QueryBeaconRequest requests the VrfBeacon for the current context height.
// Historical requests use the ABCI height parameter; no explicit height field
// is needed here.
type QueryBeaconRequest struct {
}

func (m *QueryBeaconRequest) Reset()         { *m = QueryBeaconRequest{} }
func (m *QueryBeaconRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBeaconRequest) ProtoMessage()    {}
func (*QueryBeaconRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0eafac98a734a97, []int{2}
}
func (m *QueryBeaconRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBeaconRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBeaconRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBeaconRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBeaconRequest.Merge(m, src)
}
func (m *QueryBeaconRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBeaconRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBeaconRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBeaconRequest proto.InternalMessageInfo

// QueryBeaconResponse carries the canonical VrfBeacon for the requested height.
type QueryBeaconResponse struct {
	Beacon VrfBeacon `protobuf:"bytes,1,opt,name=beacon,proto3" json:"beacon"`
}

func (m *QueryBeaconResponse) Reset()         { *m = QueryBeaconResponse{} }
func (m *QueryBeaconResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBeaconResponse) ProtoMessage()    {}
func (*QueryBeaconResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0eafac98a734a97, []int{3}
}
func (m *QueryBeaconResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBeaconResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBeaconResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBeaconResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBeaconResponse.Merge(m, src)
}
func (m *QueryBeaconResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBeaconResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBeaconResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBeaconResponse proto.InternalMessageInfo

func (m *QueryBeaconResponse) GetBeacon() VrfBeacon {
	if m != nil {
		return m.Beacon
	}
	return VrfBeacon{}
}

// QueryRandomWordsRequest requests N random words derived from the beacon at
// the current context height, using the derivation described in the PRD.
type QueryRandomWordsRequest struct {
	// count is the number of random words to derive.
	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// user_seed is an application-supplied seed that is mixed into the
	// derivation to give callers domain separation.
	UserSeed []byte `protobuf:"bytes,2,opt,name=user_seed,json=userSeed,proto3" json:"user_seed,omitempty"`
}

func (m *QueryRandomWordsRequest) Reset()         { *m = QueryRandomWordsRequest{} }
func (m *QueryRandomWordsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryRandomWordsRequest) ProtoMessage()    {}
func (*QueryRandomWordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0eafac98a734a97, []int{4}
}
func (m *QueryRandomWordsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomWordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomWordsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomWordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomWordsRequest.Merge(m, src)
}
func (m *QueryRandomWordsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomWordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomWordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomWordsRequest proto.InternalMessageInfo

func (m *QueryRandomWordsRequest) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *QueryRandomWordsRequest) GetUserSeed() []byte {
	if m != nil {
		return m.UserSeed
	}
	return nil
}

// QueryRandomWordsResponse returns the underlying drand round, the raw seed,
// and the derived random words.
type QueryRandomWordsResponse struct {
	DrandRound uint64   `protobuf:"varint,1,opt,name=drand_round,json=drandRound,proto3" json:"drand_round,omitempty"`
	Seed       []byte   `protobuf:"bytes,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Words      [][]byte `protobuf:"bytes,3,rep,name=words,proto3" json:"words,omitempty"`
}

func (m *QueryRandomWordsResponse) Reset()         { *m = QueryRandomWordsResponse{} }
func (m *QueryRandomWordsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryRandomWordsResponse) ProtoMessage()    {}
func (*QueryRandomWordsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0eafac98a734a97, []int{5}
}
func (m *QueryRandomWordsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryRandomWordsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryRandomWordsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryRandomWordsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryRandomWordsResponse.Merge(m, src)
}
func (m *QueryRandomWordsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryRandomWordsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryRandomWordsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryRandomWordsResponse proto.InternalMessageInfo

func (m *QueryRandomWordsResponse) GetDrandRound() uint64 {
	if m != nil {
		return m.DrandRound
	}
	return 0
}

func (m *QueryRandomWordsResponse) GetSeed() []byte {
	if m != nil {
		return m.Seed
	}
	return nil
}

func (m *QueryRandomWordsResponse) GetWords() [][]byte {
	if m != nil {
		return m.Words
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "vexxvakan.vrf.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "vexxvakan.vrf.v1.QueryParamsResponse")
	proto.RegisterType((*QueryBeaconRequest)(nil), "vexxvakan.vrf.v1.QueryBeaconRequest")
	proto.RegisterType((*QueryBeaconResponse)(nil), "vexxvakan.vrf.v1.QueryBeaconResponse")
	proto.RegisterType((*QueryRandomWordsRequest)(nil), "vexxvakan.vrf.v1.QueryRandomWordsRequest")
	proto.RegisterType((*QueryRandomWordsResponse)(nil), "vexxvakan.vrf.v1.QueryRandomWordsResponse")
}

func init() { proto.RegisterFile("vexxvakan/vrf/v1/query.proto", fileDescriptor_a0eafac98a734a97) }

var fileDescriptor_a0eafac98a734a97 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0xd3, 0x36, 0xa2, 0x97, 0x82, 0xca, 0x11, 0x41, 0xe4, 0x54, 0x6e, 0xb0, 0x8a, 0x14,
	0x3a, 0xd8, 0x6a, 0xd9, 0x3b, 0x64, 0x66, 0x80, 0x43, 0x80, 0xc4, 0x12, 0x5d, 0xe2, 0x8b, 0xb1,
	0xc0, 0xf7, 0xdc, 0x3b, 0xdb, 0xa4, 0x2b, 0x0b, 0x8c, 0x48, 0xfc, 0x09, 0x46, 0x7e, 0x46, 0xc7,
	0x4a, 0x2c, 0x4c, 0x08, 0x25, 0x48, 0xfc, 0x06, 0x36, 0x74, 0x77, 0x76, 0x1b, 0xc7, 0x0a, 0x74,
	0xb1, 0xee, 0xbe, 0xf7, 0xde, 0xf7, 0x7d, 0xef, 0x3d, 0x1f, 0xda, 0xcb, 0xd9, 0x6c, 0x96, 0xd3,
	0x37, 0x94, 0xfb, 0xb9, 0x98, 0xfa, 0xf9, 0x91, 0x7f, 0x9a, 0x31, 0x71, 0xe6, 0x25, 0x02, 0x52,
	0xc0, 0xbb, 0x97, 0x51, 0x2f, 0x17, 0x53, 0x2f, 0x3f, 0xb2, 0x6f, 0xd3, 0x38, 0xe2, 0xe0, 0xeb,
	0xaf, 0x49, 0xb2, 0x7b, 0x13, 0x90, 0x31, 0x48, 0x53, 0xb8, 0xc2, 0x60, 0x77, 0x42, 0x08, 0x41,
	0x1f, 0x7d, 0x75, 0x2a, 0xd0, 0xbd, 0x10, 0x20, 0x7c, 0xcb, 0x7c, 0x9a, 0x44, 0x3e, 0xe5, 0x1c,
	0x52, 0x9a, 0x46, 0xc0, 0x65, 0x11, 0x75, 0x6a, 0x9e, 0x42, 0xc6, 0x99, 0x8c, 0xca, 0xb8, 0x5d,
	0x8b, 0x2b, 0x73, 0x3a, 0xe6, 0x76, 0x10, 0x7e, 0xaa, 0xe4, 0x9f, 0x50, 0x41, 0x63, 0x49, 0xd8,
	0x69, 0xc6, 0x64, 0xea, 0x3e, 0x47, 0x77, 0x2a, 0xa8, 0x4c, 0x80, 0x4b, 0x86, 0x4f, 0x50, 0x2b,
	0xd1, 0x48, 0xd7, 0xea, 0x5b, 0x83, 0xf6, 0x71, 0xcf, 0x5b, 0xed, 0xd7, 0x7b, 0x21, 0xa6, 0xa6,
	0x68, 0xb8, 0x7d, 0xfe, 0x63, 0xbf, 0xf1, 0xe5, 0xf7, 0xd7, 0x43, 0x8b, 0x14, 0x55, 0x97, 0x62,
	0x43, 0x46, 0x27, 0xc0, 0x57, 0xc5, 0x4a, 0xf4, 0x4a, 0x6c, 0xac, 0x91, 0x7f, 0x8a, 0x99, 0xa2,
	0x8a, 0x98, 0xa9, 0x72, 0x1f, 0xa3, 0x7b, 0x9a, 0x96, 0x50, 0x1e, 0x40, 0xfc, 0x12, 0x44, 0x50,
	0xb6, 0x87, 0x3b, 0x68, 0x6b, 0x02, 0x19, 0x4f, 0x35, 0xf3, 0x4d, 0x62, 0x2e, 0xb8, 0x87, 0xb6,
	0x33, 0xc9, 0xc4, 0x48, 0x32, 0x16, 0x74, 0x9b, 0x7d, 0x6b, 0xb0, 0x43, 0x6e, 0x28, 0xe0, 0x19,
	0x63, 0x81, 0xcb, 0x50, 0xb7, 0xce, 0x56, 0x38, 0xdd, 0x47, 0xed, 0x40, 0x50, 0x1e, 0x8c, 0x04,
	0x64, 0x3c, 0xd0, 0xa4, 0x9b, 0x04, 0x69, 0x88, 0x28, 0x04, 0x63, 0xb4, 0xb9, 0x44, 0xaa, 0xcf,
	0xca, 0xc3, 0x3b, 0xc5, 0xd2, 0xdd, 0xe8, 0x6f, 0x0c, 0x76, 0x88, 0xb9, 0x1c, 0xff, 0x69, 0xa2,
	0x2d, 0xad, 0x83, 0x05, 0x6a, 0x99, 0x41, 0xe2, 0x83, 0x7a, 0xe3, 0xf5, 0x95, 0xd9, 0x0f, 0xfe,
	0x93, 0x65, 0xbc, 0xba, 0xbd, 0x8f, 0x6a, 0x48, 0xef, 0xbf, 0xfd, 0xfa, 0xdc, 0xdc, 0xc5, 0xb7,
	0xca, 0xff, 0xc1, 0xec, 0x47, 0x69, 0x9a, 0x79, 0xae, 0xd5, 0xac, 0x6c, 0x6e, 0xad, 0x66, 0x75,
	0x93, 0x6b, 0x34, 0xcd, 0x9a, 0xf0, 0x07, 0x0b, 0xb5, 0x97, 0x86, 0x8a, 0x1f, 0xae, 0xe1, 0xac,
	0xaf, 0xd1, 0x3e, 0xbc, 0x4e, 0x6a, 0xe1, 0xe1, 0xfe, 0x95, 0x87, 0xbb, 0xb8, 0x53, 0x7a, 0x10,
	0x3a, 0x73, 0xa4, 0x67, 0x3f, 0x3c, 0x39, 0x9f, 0x3b, 0xd6, 0xc5, 0xdc, 0xb1, 0x7e, 0xce, 0x1d,
	0xeb, 0xd3, 0xc2, 0x69, 0x5c, 0x2c, 0x9c, 0xc6, 0xf7, 0x85, 0xd3, 0x78, 0x75, 0x10, 0x46, 0xe9,
	0xeb, 0x6c, 0xec, 0x4d, 0x20, 0xf6, 0xab, 0x6f, 0x69, 0xa6, 0xbf, 0xe9, 0x59, 0xc2, 0xe4, 0xb8,
	0xa5, 0x5f, 0xd4, 0xa3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x2b, 0x8c, 0xb0, 0x23, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the on-chain VRF parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Beacon returns the latest VrfBeacon for the current or specified height
	Beacon(ctx context.Context, in *QueryBeaconRequest, opts ...grpc.CallOption) (*QueryBeaconResponse, error)
	// RandomWords expands the current block's VRF seed into N random words
	RandomWords(ctx context.Context, in *QueryRandomWordsRequest, opts ...grpc.CallOption) (*QueryRandomWordsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/vexxvakan.vrf.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Beacon(ctx context.Context, in *QueryBeaconRequest, opts ...grpc.CallOption) (*QueryBeaconResponse, error) {
	out := new(QueryBeaconResponse)
	err := c.cc.Invoke(ctx, "/vexxvakan.vrf.v1.Query/Beacon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RandomWords(ctx context.Context, in *QueryRandomWordsRequest, opts ...grpc.CallOption) (*QueryRandomWordsResponse, error) {
	out := new(QueryRandomWordsResponse)
	err := c.cc.Invoke(ctx, "/vexxvakan.vrf.v1.Query/RandomWords", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the on-chain VRF parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Beacon returns the latest VrfBeacon for the current or specified height
	Beacon(context.Context, *QueryBeaconRequest) (*QueryBeaconResponse, error)
	// RandomWords expands the current block's VRF seed into N random words
	RandomWords(context.Context, *QueryRandomWordsRequest) (*QueryRandomWordsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Beacon(ctx context.Context, req *QueryBeaconRequest) (*QueryBeaconResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Beacon not implemented")
}
func (*UnimplementedQueryServer) RandomWords(ctx context.Context, req *QueryRandomWordsRequest) (*QueryRandomWordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RandomWords not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vexxvakan.vrf.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Beacon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBeaconRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Beacon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vexxvakan.vrf.v1.Query/Beacon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Beacon(ctx, req.(*QueryBeaconRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RandomWords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRandomWordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RandomWords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vexxvakan.vrf.v1.Query/RandomWords",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RandomWords(ctx, req.(*QueryRandomWordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vexxvakan.vrf.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Beacon",
			Handler:    _Query_Beacon_Handler,
		},
		{
			MethodName: "RandomWords",
			Handler:    _Query_RandomWords_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vexxvakan/vrf/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBeaconRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBeaconRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBeaconRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryBeaconResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBeaconResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBeaconResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Beacon.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryRandomWordsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomWordsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomWordsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UserSeed) > 0 {
		i -= len(m.UserSeed)
		copy(dAtA[i:], m.UserSeed)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UserSeed)))
		i--
		dAtA[i] = 0x12
	}
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryRandomWordsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryRandomWordsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryRandomWordsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Words) > 0 {
		for iNdEx := len(m.Words) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Words[iNdEx])
			copy(dAtA[i:], m.Words[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Words[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Seed) > 0 {
		i -= len(m.Seed)
		copy(dAtA[i:], m.Seed)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Seed)))
		i--
		dAtA[i] = 0x12
	}
	if m.DrandRound != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.DrandRound))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBeaconRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryBeaconResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Beacon.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryRandomWordsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	l = len(m.UserSeed)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryRandomWordsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DrandRound != 0 {
		n += 1 + sovQuery(uint64(m.DrandRound))
	}
	l = len(m.Seed)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Words) > 0 {
		for _, b := range m.Words {
			l = len(b)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBeaconRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBeaconRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBeaconRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBeaconResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBeaconResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBeaconResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Beacon", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Beacon.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRandomWordsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomWordsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomWordsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserSeed", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserSeed = append(m.UserSeed[:0], dAtA[iNdEx:postIndex]...)
			if m.UserSeed == nil {
				m.UserSeed = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryRandomWordsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryRandomWordsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryRandomWordsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandRound", wireType)
			}
			m.DrandRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DrandRound |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seed", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seed = append(m.Seed[:0], dAtA[iNdEx:postIndex]...)
			if m.Seed == nil {
				m.Seed = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Words", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Words = append(m.Words, make([]byte, postIndex-iNdEx))
			copy(m.Words[len(m.Words)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
