// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: digitalkitchen/vrf/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgVrfEmergencyDisable is a gasless, committee-only message that requests
// emergency disabling of VRF for the chain. The effective state change
// (toggling VrfParams.enabled = false) is handled in PreBlock once an
// authorized transaction including this message has been verified.
type MsgVrfEmergencyDisable struct {
	// authority is the Bech32 address of the signer requesting emergency disable.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// reason is a free-form, human-readable description of why VRF is being
	// disabled. It is emitted in events and recorded off-chain for operator
	// accountability.
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgVrfEmergencyDisable) Reset()         { *m = MsgVrfEmergencyDisable{} }
func (m *MsgVrfEmergencyDisable) String() string { return proto.CompactTextString(m) }
func (*MsgVrfEmergencyDisable) ProtoMessage()    {}
func (*MsgVrfEmergencyDisable) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{0}
}
func (m *MsgVrfEmergencyDisable) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVrfEmergencyDisable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVrfEmergencyDisable.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVrfEmergencyDisable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVrfEmergencyDisable.Merge(m, src)
}
func (m *MsgVrfEmergencyDisable) XXX_Size() int {
	return m.Size()
}
func (m *MsgVrfEmergencyDisable) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVrfEmergencyDisable.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVrfEmergencyDisable proto.InternalMessageInfo

func (m *MsgVrfEmergencyDisable) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgVrfEmergencyDisable) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// MsgVrfEmergencyDisableResponse is returned on successful delivery of
// MsgVrfEmergencyDisable. The actual state transition is performed in PreBlock.
type MsgVrfEmergencyDisableResponse struct {
}

func (m *MsgVrfEmergencyDisableResponse) Reset()         { *m = MsgVrfEmergencyDisableResponse{} }
func (m *MsgVrfEmergencyDisableResponse) String() string { return proto.CompactTextString(m) }
func (*MsgVrfEmergencyDisableResponse) ProtoMessage()    {}
func (*MsgVrfEmergencyDisableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{1}
}
func (m *MsgVrfEmergencyDisableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgVrfEmergencyDisableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgVrfEmergencyDisableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgVrfEmergencyDisableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgVrfEmergencyDisableResponse.Merge(m, src)
}
func (m *MsgVrfEmergencyDisableResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgVrfEmergencyDisableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgVrfEmergencyDisableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgVrfEmergencyDisableResponse proto.InternalMessageInfo

// MsgInitialDkg sets the initial drand chain-info required to bootstrap VRF.
type MsgInitialDkg struct {
	// initiator is the bech32 account address initiating initial DKG bootstrap.
	Initiator string `protobuf:"bytes,1,opt,name=initiator,proto3" json:"initiator,omitempty"`
	// chain_hash is the drand chain hash identifier.
	ChainHash []byte `protobuf:"bytes,2,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
	// public_key is the drand collective BLS public key.
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// period_seconds is the drand beacon period in seconds.
	PeriodSeconds uint64 `protobuf:"varint,4,opt,name=period_seconds,json=periodSeconds,proto3" json:"period_seconds,omitempty"`
	// genesis_unix_sec is the drand genesis time (UNIX seconds) for round 1.
	GenesisUnixSec int64 `protobuf:"varint,5,opt,name=genesis_unix_sec,json=genesisUnixSec,proto3" json:"genesis_unix_sec,omitempty"`
}

func (m *MsgInitialDkg) Reset()         { *m = MsgInitialDkg{} }
func (m *MsgInitialDkg) String() string { return proto.CompactTextString(m) }
func (*MsgInitialDkg) ProtoMessage()    {}
func (*MsgInitialDkg) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{2}
}
func (m *MsgInitialDkg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitialDkg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitialDkg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitialDkg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitialDkg.Merge(m, src)
}
func (m *MsgInitialDkg) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitialDkg) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitialDkg.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitialDkg proto.InternalMessageInfo

// MsgInitialDkgResponse is returned on successful delivery of MsgInitialDkg.
type MsgInitialDkgResponse struct {
}

func (m *MsgInitialDkgResponse) Reset()         { *m = MsgInitialDkgResponse{} }
func (m *MsgInitialDkgResponse) String() string { return proto.CompactTextString(m) }
func (*MsgInitialDkgResponse) ProtoMessage()    {}
func (*MsgInitialDkgResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{3}
}
func (m *MsgInitialDkgResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgInitialDkgResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgInitialDkgResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgInitialDkgResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgInitialDkgResponse.Merge(m, src)
}
func (m *MsgInitialDkgResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgInitialDkgResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgInitialDkgResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgInitialDkgResponse proto.InternalMessageInfo

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address of the governance account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the x/vrf parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params VrfParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{4}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

// MsgUpdateParamsResponse is returned on successful delivery of MsgUpdateParams.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{5}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

// MsgAddVrfCommitteeMember adds or updates an account in the VRF committee allowlist.
type MsgAddVrfCommitteeMember struct {
	// authority is the address of the governance account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// address is the account to add to the committee.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// label is free-form metadata for auditing.
	Label string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
}

func (m *MsgAddVrfCommitteeMember) Reset()         { *m = MsgAddVrfCommitteeMember{} }
func (m *MsgAddVrfCommitteeMember) String() string { return proto.CompactTextString(m) }
func (*MsgAddVrfCommitteeMember) ProtoMessage()    {}
func (*MsgAddVrfCommitteeMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{6}
}
func (m *MsgAddVrfCommitteeMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddVrfCommitteeMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddVrfCommitteeMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddVrfCommitteeMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddVrfCommitteeMember.Merge(m, src)
}
func (m *MsgAddVrfCommitteeMember) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddVrfCommitteeMember) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddVrfCommitteeMember.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddVrfCommitteeMember proto.InternalMessageInfo

// MsgAddVrfCommitteeMemberResponse is returned on successful delivery of
// MsgAddVrfCommitteeMember.
type MsgAddVrfCommitteeMemberResponse struct {
}

func (m *MsgAddVrfCommitteeMemberResponse) Reset()         { *m = MsgAddVrfCommitteeMemberResponse{} }
func (m *MsgAddVrfCommitteeMemberResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddVrfCommitteeMemberResponse) ProtoMessage()    {}
func (*MsgAddVrfCommitteeMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{7}
}
func (m *MsgAddVrfCommitteeMemberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddVrfCommitteeMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddVrfCommitteeMemberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddVrfCommitteeMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddVrfCommitteeMemberResponse.Merge(m, src)
}
func (m *MsgAddVrfCommitteeMemberResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddVrfCommitteeMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddVrfCommitteeMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddVrfCommitteeMemberResponse proto.InternalMessageInfo

// MsgRemoveVrfCommitteeMember removes an account from the VRF committee allowlist.
type MsgRemoveVrfCommitteeMember struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *MsgRemoveVrfCommitteeMember) Reset()         { *m = MsgRemoveVrfCommitteeMember{} }
func (m *MsgRemoveVrfCommitteeMember) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveVrfCommitteeMember) ProtoMessage()    {}
func (*MsgRemoveVrfCommitteeMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{8}
}
func (m *MsgRemoveVrfCommitteeMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveVrfCommitteeMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveVrfCommitteeMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveVrfCommitteeMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveVrfCommitteeMember.Merge(m, src)
}
func (m *MsgRemoveVrfCommitteeMember) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveVrfCommitteeMember) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveVrfCommitteeMember.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveVrfCommitteeMember proto.InternalMessageInfo

// MsgRemoveVrfCommitteeMemberResponse is returned on successful delivery of
// MsgRemoveVrfCommitteeMember.
type MsgRemoveVrfCommitteeMemberResponse struct {
}

func (m *MsgRemoveVrfCommitteeMemberResponse) Reset()         { *m = MsgRemoveVrfCommitteeMemberResponse{} }
func (m *MsgRemoveVrfCommitteeMemberResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveVrfCommitteeMemberResponse) ProtoMessage()    {}
func (*MsgRemoveVrfCommitteeMemberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{9}
}
func (m *MsgRemoveVrfCommitteeMemberResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveVrfCommitteeMemberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveVrfCommitteeMemberResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveVrfCommitteeMemberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveVrfCommitteeMemberResponse.Merge(m, src)
}
func (m *MsgRemoveVrfCommitteeMemberResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveVrfCommitteeMemberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveVrfCommitteeMemberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveVrfCommitteeMemberResponse proto.InternalMessageInfo

// MsgRegisterVrfIdentity binds a validator operator to its drand BLS identity/share.
type MsgRegisterVrfIdentity struct {
	// operator is the bech32 account address controlling the validator.
	// The corresponding validator operator address is derived from this value.
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// drand_bls_public_key is the validator's drand BLS public key/share.
	DrandBlsPublicKey []byte `protobuf:"bytes,2,opt,name=drand_bls_public_key,json=drandBlsPublicKey,proto3" json:"drand_bls_public_key,omitempty"`
}

func (m *MsgRegisterVrfIdentity) Reset()         { *m = MsgRegisterVrfIdentity{} }
func (m *MsgRegisterVrfIdentity) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterVrfIdentity) ProtoMessage()    {}
func (*MsgRegisterVrfIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{10}
}
func (m *MsgRegisterVrfIdentity) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterVrfIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterVrfIdentity.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterVrfIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterVrfIdentity.Merge(m, src)
}
func (m *MsgRegisterVrfIdentity) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterVrfIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterVrfIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterVrfIdentity proto.InternalMessageInfo

// MsgRegisterVrfIdentityResponse is returned on successful delivery of
// MsgRegisterVrfIdentity.
type MsgRegisterVrfIdentityResponse struct {
}

func (m *MsgRegisterVrfIdentityResponse) Reset()         { *m = MsgRegisterVrfIdentityResponse{} }
func (m *MsgRegisterVrfIdentityResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterVrfIdentityResponse) ProtoMessage()    {}
func (*MsgRegisterVrfIdentityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{11}
}
func (m *MsgRegisterVrfIdentityResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterVrfIdentityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterVrfIdentityResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterVrfIdentityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterVrfIdentityResponse.Merge(m, src)
}
func (m *MsgRegisterVrfIdentityResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterVrfIdentityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterVrfIdentityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterVrfIdentityResponse proto.InternalMessageInfo

// MsgScheduleVrfReshare increments VrfParams.reshare_epoch to signal a new
// resharing round.
type MsgScheduleVrfReshare struct {
	// scheduler is the account requesting the reshare (must be a committee member).
	Scheduler string `protobuf:"bytes,1,opt,name=scheduler,proto3" json:"scheduler,omitempty"`
	// reshare_epoch is the new reshare epoch value (must be strictly greater than the current).
	ReshareEpoch uint64 `protobuf:"varint,2,opt,name=reshare_epoch,json=reshareEpoch,proto3" json:"reshare_epoch,omitempty"`
	// reason is a free-form human-readable description of why resharing is being scheduled.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (m *MsgScheduleVrfReshare) Reset()         { *m = MsgScheduleVrfReshare{} }
func (m *MsgScheduleVrfReshare) String() string { return proto.CompactTextString(m) }
func (*MsgScheduleVrfReshare) ProtoMessage()    {}
func (*MsgScheduleVrfReshare) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{12}
}
func (m *MsgScheduleVrfReshare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgScheduleVrfReshare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgScheduleVrfReshare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgScheduleVrfReshare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgScheduleVrfReshare.Merge(m, src)
}
func (m *MsgScheduleVrfReshare) XXX_Size() int {
	return m.Size()
}
func (m *MsgScheduleVrfReshare) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgScheduleVrfReshare.DiscardUnknown(m)
}

var xxx_messageInfo_MsgScheduleVrfReshare proto.InternalMessageInfo

// MsgScheduleVrfReshareResponse is returned on successful delivery of
// MsgScheduleVrfReshare.
type MsgScheduleVrfReshareResponse struct {
}

func (m *MsgScheduleVrfReshareResponse) Reset()         { *m = MsgScheduleVrfReshareResponse{} }
func (m *MsgScheduleVrfReshareResponse) String() string { return proto.CompactTextString(m) }
func (*MsgScheduleVrfReshareResponse) ProtoMessage()    {}
func (*MsgScheduleVrfReshareResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a678cd2e95c8cef8, []int{13}
}
func (m *MsgScheduleVrfReshareResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgScheduleVrfReshareResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgScheduleVrfReshareResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgScheduleVrfReshareResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgScheduleVrfReshareResponse.Merge(m, src)
}
func (m *MsgScheduleVrfReshareResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgScheduleVrfReshareResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgScheduleVrfReshareResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgScheduleVrfReshareResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgVrfEmergencyDisable)(nil), "digitalkitchen.vrf.v1.MsgVrfEmergencyDisable")
	proto.RegisterType((*MsgVrfEmergencyDisableResponse)(nil), "digitalkitchen.vrf.v1.MsgVrfEmergencyDisableResponse")
	proto.RegisterType((*MsgInitialDkg)(nil), "digitalkitchen.vrf.v1.MsgInitialDkg")
	proto.RegisterType((*MsgInitialDkgResponse)(nil), "digitalkitchen.vrf.v1.MsgInitialDkgResponse")
	proto.RegisterType((*MsgUpdateParams)(nil), "digitalkitchen.vrf.v1.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "digitalkitchen.vrf.v1.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgAddVrfCommitteeMember)(nil), "digitalkitchen.vrf.v1.MsgAddVrfCommitteeMember")
	proto.RegisterType((*MsgAddVrfCommitteeMemberResponse)(nil), "digitalkitchen.vrf.v1.MsgAddVrfCommitteeMemberResponse")
	proto.RegisterType((*MsgRemoveVrfCommitteeMember)(nil), "digitalkitchen.vrf.v1.MsgRemoveVrfCommitteeMember")
	proto.RegisterType((*MsgRemoveVrfCommitteeMemberResponse)(nil), "digitalkitchen.vrf.v1.MsgRemoveVrfCommitteeMemberResponse")
	proto.RegisterType((*MsgRegisterVrfIdentity)(nil), "digitalkitchen.vrf.v1.MsgRegisterVrfIdentity")
	proto.RegisterType((*MsgRegisterVrfIdentityResponse)(nil), "digitalkitchen.vrf.v1.MsgRegisterVrfIdentityResponse")
	proto.RegisterType((*MsgScheduleVrfReshare)(nil), "digitalkitchen.vrf.v1.MsgScheduleVrfReshare")
	proto.RegisterType((*MsgScheduleVrfReshareResponse)(nil), "digitalkitchen.vrf.v1.MsgScheduleVrfReshareResponse")
}

func init() { proto.RegisterFile("digitalkitchen/vrf/v1/tx.proto", fileDescriptor_a678cd2e95c8cef8) }

var fileDescriptor_a678cd2e95c8cef8 = []byte{
	// 922 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0xcf, 0x6b, 0xdc, 0x46,
	0x14, 0x5e, 0xc5, 0x3f, 0x5a, 0xbf, 0xda, 0x69, 0xa3, 0xd8, 0xf1, 0x5a, 0x25, 0xbb, 0x8b, 0x5c,
	0x07, 0x63, 0xea, 0x15, 0xd9, 0xb8, 0x2d, 0x2c, 0xb4, 0x24, 0x6e, 0x02, 0x0d, 0x65, 0x21, 0xc8,
	0xc4, 0x87, 0x5e, 0x54, 0xad, 0x34, 0x3b, 0x1a, 0x2c, 0x69, 0xc4, 0xcc, 0xec, 0xb2, 0x4b, 0x2e,
	0x6d, 0x4f, 0xc5, 0xa7, 0xfe, 0x03, 0x85, 0xfc, 0x09, 0x3e, 0xf4, 0xd6, 0x43, 0xaf, 0x86, 0x5e,
	0x42, 0x4f, 0x85, 0x40, 0x29, 0xf6, 0xc1, 0xfd, 0x33, 0x8a, 0x34, 0x5a, 0xed, 0xaa, 0x96, 0xb6,
	0x76, 0x2e, 0xb9, 0x2c, 0x3b, 0xef, 0x7d, 0xef, 0xcd, 0xf7, 0x3d, 0xcd, 0x7c, 0x12, 0xd4, 0x5c,
	0x82, 0x89, 0xb0, 0xfd, 0x23, 0x22, 0x1c, 0x0f, 0x85, 0xc6, 0x80, 0xf5, 0x8c, 0xc1, 0x7d, 0x43,
	0x0c, 0x9b, 0x11, 0xa3, 0x82, 0xaa, 0x6b, 0xf9, 0x7c, 0x73, 0xc0, 0x7a, 0xcd, 0xc1, 0x7d, 0xed,
	0x96, 0x1d, 0x90, 0x90, 0x1a, 0xc9, 0xaf, 0x44, 0x6a, 0xeb, 0x0e, 0xe5, 0x01, 0xe5, 0x46, 0xc0,
	0x71, 0xdc, 0x21, 0xe0, 0x38, 0x4d, 0x6c, 0xc8, 0x84, 0x95, 0xac, 0x0c, 0xb9, 0x48, 0x53, 0x9b,
	0xc5, 0xbb, 0x63, 0x14, 0x22, 0x4e, 0xc6, 0xa0, 0x55, 0x4c, 0x31, 0x95, 0xc5, 0xf1, 0x3f, 0x19,
	0xd5, 0x7f, 0x56, 0xe0, 0x4e, 0x87, 0xe3, 0x43, 0xd6, 0x7b, 0x12, 0x20, 0x86, 0x51, 0xe8, 0x8c,
	0x1e, 0x13, 0x6e, 0x77, 0x7d, 0xa4, 0x7e, 0x0a, 0x4b, 0x76, 0x5f, 0x78, 0x94, 0x11, 0x31, 0xaa,
	0x2a, 0x0d, 0x65, 0x7b, 0x69, 0xbf, 0xfa, 0xc7, 0x2f, 0xbb, 0xab, 0xe9, 0xd6, 0x8f, 0x5c, 0x97,
	0x21, 0xce, 0x0f, 0x04, 0x23, 0x21, 0x36, 0x27, 0x50, 0xf5, 0x0e, 0x2c, 0x32, 0x64, 0x73, 0x1a,
	0x56, 0x6f, 0xc4, 0x45, 0x66, 0xba, 0x6a, 0x3f, 0xf8, 0xe1, 0xe2, 0x64, 0x67, 0x82, 0x3b, 0xbe,
	0x38, 0xd9, 0x69, 0xc4, 0x4c, 0x87, 0x09, 0xdf, 0x62, 0x12, 0x7a, 0x03, 0x6a, 0xc5, 0x19, 0x13,
	0xf1, 0x88, 0x86, 0x1c, 0xe9, 0xc7, 0x37, 0x60, 0xa5, 0xc3, 0xf1, 0xd3, 0x90, 0x08, 0x62, 0xfb,
	0x8f, 0x8f, 0x70, 0x4c, 0x9c, 0x24, 0x2b, 0x41, 0xd9, 0xff, 0x13, 0xcf, 0xa0, 0xea, 0x5d, 0x00,
	0xc7, 0xb3, 0x49, 0x68, 0x79, 0x36, 0xf7, 0x12, 0xf2, 0xcb, 0xe6, 0x52, 0x12, 0xf9, 0xca, 0xe6,
	0x5e, 0x9c, 0x8e, 0xfa, 0x5d, 0x9f, 0x38, 0xd6, 0x11, 0x1a, 0x55, 0xe7, 0x64, 0x5a, 0x46, 0xbe,
	0x46, 0x23, 0x75, 0x0b, 0x6e, 0x46, 0x88, 0x11, 0xea, 0x5a, 0x1c, 0x39, 0x34, 0x74, 0x79, 0x75,
	0xbe, 0xa1, 0x6c, 0xcf, 0x9b, 0x2b, 0x32, 0x7a, 0x20, 0x83, 0xea, 0x36, 0x7c, 0x90, 0x3e, 0x17,
	0xab, 0x1f, 0x92, 0x61, 0x0c, 0xae, 0x2e, 0x34, 0x94, 0xed, 0x39, 0xf3, 0x66, 0x1a, 0x7f, 0x1e,
	0x92, 0xe1, 0x01, 0x72, 0xda, 0xad, 0x1f, 0x5f, 0xd6, 0x2b, 0xff, 0xbc, 0xac, 0x57, 0x92, 0xb9,
	0x65, 0x34, 0xe3, 0xb9, 0xad, 0xe7, 0xe6, 0x36, 0x91, 0xae, 0xaf, 0xc3, 0x5a, 0x2e, 0x90, 0x4d,
	0xe9, 0x37, 0x05, 0xde, 0xef, 0x70, 0xfc, 0x3c, 0x72, 0x6d, 0x81, 0x9e, 0xd9, 0xcc, 0x0e, 0xf8,
	0x1b, 0x3f, 0xe0, 0x2f, 0x60, 0x31, 0x4a, 0x3a, 0x24, 0x33, 0x7a, 0xaf, 0xd5, 0x68, 0x16, 0x9e,
	0xee, 0xe6, 0x21, 0xeb, 0xc9, 0x9d, 0xf6, 0xe7, 0x4f, 0xff, 0xaa, 0x57, 0xcc, 0xb4, 0xaa, 0xbd,
	0x97, 0x13, 0x96, 0x3b, 0x10, 0x1b, 0x39, 0x61, 0xd3, 0x6c, 0xf5, 0x0d, 0x58, 0xff, 0x4f, 0x28,
	0x13, 0xf7, 0x5a, 0x81, 0x6a, 0x87, 0xe3, 0x47, 0xae, 0x7b, 0xc8, 0x7a, 0x5f, 0xd2, 0x20, 0x20,
	0x42, 0x20, 0xd4, 0x41, 0x41, 0x17, 0xb1, 0x37, 0x56, 0xd9, 0x82, 0x77, 0x6c, 0x99, 0x93, 0xe7,
	0x78, 0x46, 0xd5, 0x18, 0xa8, 0xae, 0xc2, 0x82, 0x6f, 0x77, 0x91, 0x9f, 0x9c, 0x8e, 0x25, 0x53,
	0x2e, 0xda, 0x9f, 0x97, 0xeb, 0xd5, 0x73, 0x7a, 0x0b, 0x05, 0xe8, 0x3a, 0x34, 0xca, 0x72, 0xd9,
	0x04, 0x7e, 0x57, 0xe0, 0xc3, 0x0e, 0xc7, 0x26, 0x0a, 0xe8, 0x00, 0xbd, 0xdd, 0x21, 0xb4, 0x1f,
	0x96, 0xcb, 0xdd, 0xca, 0xc9, 0x2d, 0x63, 0xab, 0x6f, 0xc1, 0xe6, 0x8c, 0x74, 0x26, 0xfa, 0x57,
	0xe9, 0x5d, 0x26, 0xc2, 0x84, 0x0b, 0xc4, 0x0e, 0x59, 0xef, 0xa9, 0x8b, 0x42, 0x11, 0xf3, 0xde,
	0x83, 0x77, 0x69, 0x84, 0xd8, 0x95, 0x1c, 0x20, 0x43, 0xaa, 0x06, 0xac, 0xba, 0xcc, 0x0e, 0x5d,
	0xab, 0xeb, 0x73, 0x6b, 0xea, 0xae, 0x4b, 0x2b, 0xb8, 0x95, 0xe4, 0xf6, 0x7d, 0xfe, 0x6c, 0x7c,
	0xe7, 0xdb, 0xed, 0x69, 0xa9, 0x59, 0x9f, 0xcb, 0xce, 0x56, 0x40, 0x31, 0x75, 0xb6, 0x82, 0x4c,
	0xa6, 0xef, 0x54, 0x49, 0x6e, 0xf3, 0x81, 0xe3, 0x21, 0xb7, 0xef, 0xc7, 0x93, 0x30, 0x11, 0xf7,
	0x6c, 0x96, 0x58, 0x33, 0x4f, 0xa3, 0x57, 0x70, 0xb8, 0x0c, 0xaa, 0x6e, 0xc2, 0x0a, 0x93, 0x2d,
	0x2c, 0x14, 0x51, 0x47, 0x9a, 0xdc, 0xbc, 0xb9, 0x9c, 0x06, 0x9f, 0xc4, 0xb1, 0x29, 0xff, 0x9e,
	0xcb, 0xf9, 0x77, 0x4e, 0xec, 0xa4, 0x69, 0xac, 0xb6, 0x9e, 0x53, 0x7b, 0x99, 0xb0, 0x5e, 0x87,
	0xbb, 0x85, 0x89, 0xb1, 0xd6, 0xd6, 0xeb, 0x45, 0x98, 0xeb, 0x70, 0xac, 0xbe, 0x80, 0xdb, 0x45,
	0xef, 0xa2, 0xdd, 0x12, 0x8b, 0x29, 0x7e, 0x37, 0x68, 0x9f, 0x5c, 0x0b, 0x3e, 0x26, 0xa1, 0x7e,
	0x0b, 0x30, 0xf5, 0x1a, 0xf9, 0xa8, 0xbc, 0xc9, 0x04, 0xa5, 0x7d, 0x7c, 0x15, 0x54, 0xb6, 0x43,
	0x0f, 0x96, 0x73, 0x16, 0x7c, 0xaf, 0xbc, 0x7a, 0x1a, 0xa7, 0x35, 0xaf, 0x86, 0xcb, 0xf6, 0xf9,
	0x5e, 0x81, 0xb5, 0x62, 0x3b, 0x34, 0xca, 0x3b, 0x15, 0x16, 0x68, 0x9f, 0x5d, 0xb3, 0x20, 0xe3,
	0x70, 0xac, 0x40, 0xb5, 0xd4, 0x90, 0x5a, 0xe5, 0x5d, 0xcb, 0x6a, 0xb4, 0xf6, 0xf5, 0x6b, 0x32,
	0x32, 0x2f, 0xe0, 0x76, 0x91, 0x4f, 0xec, 0xce, 0x6a, 0x79, 0x09, 0x3e, 0xeb, 0x5c, 0xcd, 0xb8,
	0xc8, 0xea, 0x10, 0xd4, 0x82, 0x4b, 0x3c, 0xe3, 0xe4, 0x5c, 0x46, 0x6b, 0x7b, 0xd7, 0x41, 0x8f,
	0x77, 0xd6, 0x16, 0xbe, 0xbb, 0x38, 0xd9, 0x51, 0xf6, 0x1f, 0x9e, 0x9e, 0xd5, 0x94, 0x57, 0x67,
	0x35, 0xe5, 0xef, 0xb3, 0x9a, 0xf2, 0xd3, 0x79, 0xad, 0xf2, 0xea, 0xbc, 0x56, 0xf9, 0xf3, 0xbc,
	0x56, 0xf9, 0xe6, 0x1e, 0x26, 0xc2, 0xeb, 0x77, 0x9b, 0x0e, 0x0d, 0x0c, 0x17, 0x8b, 0xdc, 0x27,
	0xa4, 0xbc, 0xd0, 0x62, 0x14, 0x21, 0xde, 0x5d, 0x4c, 0x3e, 0x17, 0x1f, 0xfc, 0x1b, 0x00, 0x00,
	0xff, 0xff, 0x5d, 0x19, 0xdf, 0x54, 0xe9, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// VrfEmergencyDisable submits an emergency disable request. The message
	// handler is intentionally light-weight; authorization and effective
	// state change are enforced by shared logic in PreBlock and the ante
	// decorator, as described in the PRD.
	VrfEmergencyDisable(ctx context.Context, in *MsgVrfEmergencyDisable, opts ...grpc.CallOption) (*MsgVrfEmergencyDisableResponse, error)
	// InitialDkg sets the initial drand chain-info required to bootstrap VRF
	// (chain_hash, public_key, period_seconds, genesis_unix_sec). On success it
	// emits an event that off-chain listeners can use to trigger DKG/bootstrap
	// workflows and refresh sidecar configuration.
	InitialDkg(ctx context.Context, in *MsgInitialDkg, opts ...grpc.CallOption) (*MsgInitialDkgResponse, error)
	// UpdateParams defines a governance operation for updating the x/vrf module
	// parameters. The authority is expected to be the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// AddVrfCommitteeMember adds or updates a VRF committee member.
	AddVrfCommitteeMember(ctx context.Context, in *MsgAddVrfCommitteeMember, opts ...grpc.CallOption) (*MsgAddVrfCommitteeMemberResponse, error)
	// RemoveVrfCommitteeMember removes a VRF committee member.
	RemoveVrfCommitteeMember(ctx context.Context, in *MsgRemoveVrfCommitteeMember, opts ...grpc.CallOption) (*MsgRemoveVrfCommitteeMemberResponse, error)
	// RegisterVrfIdentity binds a validator to its drand identity/share.
	RegisterVrfIdentity(ctx context.Context, in *MsgRegisterVrfIdentity, opts ...grpc.CallOption) (*MsgRegisterVrfIdentityResponse, error)
	// ScheduleVrfReshare bumps VrfParams.reshare_epoch to signal resharing.
	ScheduleVrfReshare(ctx context.Context, in *MsgScheduleVrfReshare, opts ...grpc.CallOption) (*MsgScheduleVrfReshareResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) VrfEmergencyDisable(ctx context.Context, in *MsgVrfEmergencyDisable, opts ...grpc.CallOption) (*MsgVrfEmergencyDisableResponse, error) {
	out := new(MsgVrfEmergencyDisableResponse)
	err := c.cc.Invoke(ctx, "/digitalkitchen.vrf.v1.Msg/VrfEmergencyDisable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) InitialDkg(ctx context.Context, in *MsgInitialDkg, opts ...grpc.CallOption) (*MsgInitialDkgResponse, error) {
	out := new(MsgInitialDkgResponse)
	err := c.cc.Invoke(ctx, "/digitalkitchen.vrf.v1.Msg/InitialDkg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/digitalkitchen.vrf.v1.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AddVrfCommitteeMember(ctx context.Context, in *MsgAddVrfCommitteeMember, opts ...grpc.CallOption) (*MsgAddVrfCommitteeMemberResponse, error) {
	out := new(MsgAddVrfCommitteeMemberResponse)
	err := c.cc.Invoke(ctx, "/digitalkitchen.vrf.v1.Msg/AddVrfCommitteeMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveVrfCommitteeMember(ctx context.Context, in *MsgRemoveVrfCommitteeMember, opts ...grpc.CallOption) (*MsgRemoveVrfCommitteeMemberResponse, error) {
	out := new(MsgRemoveVrfCommitteeMemberResponse)
	err := c.cc.Invoke(ctx, "/digitalkitchen.vrf.v1.Msg/RemoveVrfCommitteeMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterVrfIdentity(ctx context.Context, in *MsgRegisterVrfIdentity, opts ...grpc.CallOption) (*MsgRegisterVrfIdentityResponse, error) {
	out := new(MsgRegisterVrfIdentityResponse)
	err := c.cc.Invoke(ctx, "/digitalkitchen.vrf.v1.Msg/RegisterVrfIdentity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ScheduleVrfReshare(ctx context.Context, in *MsgScheduleVrfReshare, opts ...grpc.CallOption) (*MsgScheduleVrfReshareResponse, error) {
	out := new(MsgScheduleVrfReshareResponse)
	err := c.cc.Invoke(ctx, "/digitalkitchen.vrf.v1.Msg/ScheduleVrfReshare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// VrfEmergencyDisable submits an emergency disable request. The message
	// handler is intentionally light-weight; authorization and effective
	// state change are enforced by shared logic in PreBlock and the ante
	// decorator, as described in the PRD.
	VrfEmergencyDisable(context.Context, *MsgVrfEmergencyDisable) (*MsgVrfEmergencyDisableResponse, error)
	// InitialDkg sets the initial drand chain-info required to bootstrap VRF
	// (chain_hash, public_key, period_seconds, genesis_unix_sec). On success it
	// emits an event that off-chain listeners can use to trigger DKG/bootstrap
	// workflows and refresh sidecar configuration.
	InitialDkg(context.Context, *MsgInitialDkg) (*MsgInitialDkgResponse, error)
	// UpdateParams defines a governance operation for updating the x/vrf module
	// parameters. The authority is expected to be the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// AddVrfCommitteeMember adds or updates a VRF committee member.
	AddVrfCommitteeMember(context.Context, *MsgAddVrfCommitteeMember) (*MsgAddVrfCommitteeMemberResponse, error)
	// RemoveVrfCommitteeMember removes a VRF committee member.
	RemoveVrfCommitteeMember(context.Context, *MsgRemoveVrfCommitteeMember) (*MsgRemoveVrfCommitteeMemberResponse, error)
	// RegisterVrfIdentity binds a validator to its drand identity/share.
	RegisterVrfIdentity(context.Context, *MsgRegisterVrfIdentity) (*MsgRegisterVrfIdentityResponse, error)
	// ScheduleVrfReshare bumps VrfParams.reshare_epoch to signal resharing.
	ScheduleVrfReshare(context.Context, *MsgScheduleVrfReshare) (*MsgScheduleVrfReshareResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) VrfEmergencyDisable(ctx context.Context, req *MsgVrfEmergencyDisable) (*MsgVrfEmergencyDisableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VrfEmergencyDisable not implemented")
}
func (*UnimplementedMsgServer) InitialDkg(ctx context.Context, req *MsgInitialDkg) (*MsgInitialDkgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitialDkg not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) AddVrfCommitteeMember(ctx context.Context, req *MsgAddVrfCommitteeMember) (*MsgAddVrfCommitteeMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVrfCommitteeMember not implemented")
}
func (*UnimplementedMsgServer) RemoveVrfCommitteeMember(ctx context.Context, req *MsgRemoveVrfCommitteeMember) (*MsgRemoveVrfCommitteeMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveVrfCommitteeMember not implemented")
}
func (*UnimplementedMsgServer) RegisterVrfIdentity(ctx context.Context, req *MsgRegisterVrfIdentity) (*MsgRegisterVrfIdentityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterVrfIdentity not implemented")
}
func (*UnimplementedMsgServer) ScheduleVrfReshare(ctx context.Context, req *MsgScheduleVrfReshare) (*MsgScheduleVrfReshareResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleVrfReshare not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_VrfEmergencyDisable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgVrfEmergencyDisable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).VrfEmergencyDisable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digitalkitchen.vrf.v1.Msg/VrfEmergencyDisable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).VrfEmergencyDisable(ctx, req.(*MsgVrfEmergencyDisable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_InitialDkg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgInitialDkg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).InitialDkg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digitalkitchen.vrf.v1.Msg/InitialDkg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).InitialDkg(ctx, req.(*MsgInitialDkg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digitalkitchen.vrf.v1.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AddVrfCommitteeMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddVrfCommitteeMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddVrfCommitteeMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digitalkitchen.vrf.v1.Msg/AddVrfCommitteeMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddVrfCommitteeMember(ctx, req.(*MsgAddVrfCommitteeMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveVrfCommitteeMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveVrfCommitteeMember)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveVrfCommitteeMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digitalkitchen.vrf.v1.Msg/RemoveVrfCommitteeMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveVrfCommitteeMember(ctx, req.(*MsgRemoveVrfCommitteeMember))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterVrfIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterVrfIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterVrfIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digitalkitchen.vrf.v1.Msg/RegisterVrfIdentity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterVrfIdentity(ctx, req.(*MsgRegisterVrfIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ScheduleVrfReshare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgScheduleVrfReshare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ScheduleVrfReshare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/digitalkitchen.vrf.v1.Msg/ScheduleVrfReshare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ScheduleVrfReshare(ctx, req.(*MsgScheduleVrfReshare))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "digitalkitchen.vrf.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VrfEmergencyDisable",
			Handler:    _Msg_VrfEmergencyDisable_Handler,
		},
		{
			MethodName: "InitialDkg",
			Handler:    _Msg_InitialDkg_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "AddVrfCommitteeMember",
			Handler:    _Msg_AddVrfCommitteeMember_Handler,
		},
		{
			MethodName: "RemoveVrfCommitteeMember",
			Handler:    _Msg_RemoveVrfCommitteeMember_Handler,
		},
		{
			MethodName: "RegisterVrfIdentity",
			Handler:    _Msg_RegisterVrfIdentity_Handler,
		},
		{
			MethodName: "ScheduleVrfReshare",
			Handler:    _Msg_ScheduleVrfReshare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "digitalkitchen/vrf/v1/tx.proto",
}

func (m *MsgVrfEmergencyDisable) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVrfEmergencyDisable) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVrfEmergencyDisable) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgVrfEmergencyDisableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgVrfEmergencyDisableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgVrfEmergencyDisableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgInitialDkg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitialDkg) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitialDkg) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GenesisUnixSec != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GenesisUnixSec))
		i--
		dAtA[i] = 0x28
	}
	if m.PeriodSeconds != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PeriodSeconds))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainHash) > 0 {
		i -= len(m.ChainHash)
		copy(dAtA[i:], m.ChainHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChainHash)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Initiator) > 0 {
		i -= len(m.Initiator)
		copy(dAtA[i:], m.Initiator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Initiator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgInitialDkgResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgInitialDkgResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgInitialDkgResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAddVrfCommitteeMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddVrfCommitteeMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddVrfCommitteeMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Label) > 0 {
		i -= len(m.Label)
		copy(dAtA[i:], m.Label)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Label)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddVrfCommitteeMemberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddVrfCommitteeMemberResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddVrfCommitteeMemberResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemoveVrfCommitteeMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveVrfCommitteeMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveVrfCommitteeMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveVrfCommitteeMemberResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveVrfCommitteeMemberResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveVrfCommitteeMemberResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterVrfIdentity) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterVrfIdentity) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterVrfIdentity) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DrandBlsPublicKey) > 0 {
		i -= len(m.DrandBlsPublicKey)
		copy(dAtA[i:], m.DrandBlsPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DrandBlsPublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterVrfIdentityResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterVrfIdentityResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterVrfIdentityResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgScheduleVrfReshare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgScheduleVrfReshare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgScheduleVrfReshare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reason) > 0 {
		i -= len(m.Reason)
		copy(dAtA[i:], m.Reason)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Reason)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ReshareEpoch != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ReshareEpoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Scheduler) > 0 {
		i -= len(m.Scheduler)
		copy(dAtA[i:], m.Scheduler)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Scheduler)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgScheduleVrfReshareResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgScheduleVrfReshareResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgScheduleVrfReshareResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgVrfEmergencyDisable) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgVrfEmergencyDisableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgInitialDkg) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Initiator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChainHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PeriodSeconds != 0 {
		n += 1 + sovTx(uint64(m.PeriodSeconds))
	}
	if m.GenesisUnixSec != 0 {
		n += 1 + sovTx(uint64(m.GenesisUnixSec))
	}
	return n
}

func (m *MsgInitialDkgResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAddVrfCommitteeMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Label)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAddVrfCommitteeMemberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemoveVrfCommitteeMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveVrfCommitteeMemberResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterVrfIdentity) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DrandBlsPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterVrfIdentityResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgScheduleVrfReshare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Scheduler)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.ReshareEpoch != 0 {
		n += 1 + sovTx(uint64(m.ReshareEpoch))
	}
	l = len(m.Reason)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgScheduleVrfReshareResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgVrfEmergencyDisable) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVrfEmergencyDisable: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVrfEmergencyDisable: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgVrfEmergencyDisableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgVrfEmergencyDisableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgVrfEmergencyDisableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitialDkg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitialDkg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitialDkg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Initiator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Initiator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainHash = append(m.ChainHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ChainHash == nil {
				m.ChainHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodSeconds", wireType)
			}
			m.PeriodSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodSeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisUnixSec", wireType)
			}
			m.GenesisUnixSec = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GenesisUnixSec |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgInitialDkgResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgInitialDkgResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgInitialDkgResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddVrfCommitteeMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddVrfCommitteeMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddVrfCommitteeMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Label = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddVrfCommitteeMemberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddVrfCommitteeMemberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddVrfCommitteeMemberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveVrfCommitteeMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveVrfCommitteeMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveVrfCommitteeMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveVrfCommitteeMemberResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveVrfCommitteeMemberResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveVrfCommitteeMemberResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterVrfIdentity) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterVrfIdentity: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterVrfIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandBlsPublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DrandBlsPublicKey = append(m.DrandBlsPublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.DrandBlsPublicKey == nil {
				m.DrandBlsPublicKey = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterVrfIdentityResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterVrfIdentityResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterVrfIdentityResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgScheduleVrfReshare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgScheduleVrfReshare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgScheduleVrfReshare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scheduler", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Scheduler = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReshareEpoch", wireType)
			}
			m.ReshareEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReshareEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgScheduleVrfReshareResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgScheduleVrfReshareResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgScheduleVrfReshareResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
