// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: digitalkitchen/vrf/abci/v1/vote_extension.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VrfVoteExtension carries a single drand beacon for a specific round.
type VrfVoteExtension struct {
	DrandRound        uint64 `protobuf:"varint,1,opt,name=drand_round,json=drandRound,proto3" json:"drand_round,omitempty"`
	Randomness        []byte `protobuf:"bytes,2,opt,name=randomness,proto3" json:"randomness,omitempty"`
	Signature         []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	PreviousSignature []byte `protobuf:"bytes,4,opt,name=previous_signature,json=previousSignature,proto3" json:"previous_signature,omitempty"`
	ChainHash         []byte `protobuf:"bytes,5,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
}

func (m *VrfVoteExtension) Reset()         { *m = VrfVoteExtension{} }
func (m *VrfVoteExtension) String() string { return proto.CompactTextString(m) }
func (*VrfVoteExtension) ProtoMessage()    {}
func (*VrfVoteExtension) Descriptor() ([]byte, []int) {
	return fileDescriptor_197daafdbb041096, []int{0}
}
func (m *VrfVoteExtension) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VrfVoteExtension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VrfVoteExtension.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VrfVoteExtension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VrfVoteExtension.Merge(m, src)
}
func (m *VrfVoteExtension) XXX_Size() int {
	return m.Size()
}
func (m *VrfVoteExtension) XXX_DiscardUnknown() {
	xxx_messageInfo_VrfVoteExtension.DiscardUnknown(m)
}

var xxx_messageInfo_VrfVoteExtension proto.InternalMessageInfo

func (m *VrfVoteExtension) GetDrandRound() uint64 {
	if m != nil {
		return m.DrandRound
	}
	return 0
}

func (m *VrfVoteExtension) GetRandomness() []byte {
	if m != nil {
		return m.Randomness
	}
	return nil
}

func (m *VrfVoteExtension) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *VrfVoteExtension) GetPreviousSignature() []byte {
	if m != nil {
		return m.PreviousSignature
	}
	return nil
}

func (m *VrfVoteExtension) GetChainHash() []byte {
	if m != nil {
		return m.ChainHash
	}
	return nil
}

func init() {
	proto.RegisterType((*VrfVoteExtension)(nil), "digitalkitchen.vrf.abci.v1.VrfVoteExtension")
}

func init() {
	proto.RegisterFile("digitalkitchen/vrf/abci/v1/vote_extension.proto", fileDescriptor_197daafdbb041096)
}

var fileDescriptor_197daafdbb041096 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe3, 0xff, 0x2f, 0x48, 0x18, 0x06, 0xf0, 0x14, 0x21, 0x30, 0x15, 0x53, 0x17, 0x6c,
	0x55, 0xbc, 0x01, 0x12, 0x52, 0xe7, 0x20, 0x75, 0x60, 0x89, 0x9c, 0xc4, 0x89, 0x2d, 0xa8, 0x1d,
	0xd9, 0x37, 0x56, 0x79, 0x0b, 0xde, 0x88, 0x95, 0xb1, 0x23, 0x23, 0x4a, 0x5e, 0x04, 0xc5, 0xa8,
	0xb4, 0x1d, 0xef, 0x77, 0xce, 0xb9, 0xc3, 0x87, 0x79, 0xa5, 0x1b, 0x0d, 0xe2, 0xf5, 0x45, 0x43,
	0xa9, 0xa4, 0xe1, 0xc1, 0xd5, 0x5c, 0x14, 0xa5, 0xe6, 0x61, 0xce, 0x83, 0x05, 0x99, 0xcb, 0x35,
	0x48, 0xe3, 0xb5, 0x35, 0xac, 0x75, 0x16, 0x2c, 0xb9, 0x3c, 0x1c, 0xb0, 0xe0, 0x6a, 0x36, 0x0e,
	0x58, 0x98, 0xdf, 0x7e, 0x20, 0x7c, 0xbe, 0x74, 0xf5, 0xd2, 0x82, 0x7c, 0xdc, 0xce, 0xc8, 0x0d,
	0x3e, 0xad, 0x9c, 0x30, 0x55, 0xee, 0x6c, 0x67, 0xaa, 0x14, 0x4d, 0xd1, 0x6c, 0x92, 0xe1, 0x88,
	0xb2, 0x91, 0x10, 0x8a, 0xf1, 0x78, 0xd8, 0x95, 0x91, 0xde, 0xa7, 0xff, 0xa6, 0x68, 0x76, 0x96,
	0xed, 0x11, 0x72, 0x85, 0x4f, 0xbc, 0x6e, 0x8c, 0x80, 0xce, 0xc9, 0xf4, 0x7f, 0x8c, 0x77, 0x80,
	0xdc, 0x61, 0xd2, 0x3a, 0x19, 0xb4, 0xed, 0x7c, 0xbe, 0xab, 0x4d, 0x62, 0xed, 0x62, 0x9b, 0x3c,
	0xfd, 0xd5, 0xaf, 0x31, 0x2e, 0x95, 0xd0, 0x26, 0x57, 0xc2, 0xab, 0xf4, 0xe8, 0xf7, 0x5b, 0x24,
	0x0b, 0xe1, 0xd5, 0xc3, 0xe2, 0xb3, 0xa7, 0x68, 0xd3, 0x53, 0xf4, 0xdd, 0x53, 0xf4, 0x3e, 0xd0,
	0x64, 0x33, 0xd0, 0xe4, 0x6b, 0xa0, 0xc9, 0x33, 0x6b, 0x34, 0xa8, 0xae, 0x60, 0xa5, 0x5d, 0xf1,
	0xaa, 0x81, 0x03, 0x61, 0xeb, 0x3d, 0x6d, 0x92, 0xc3, 0x5b, 0x2b, 0x7d, 0x71, 0x1c, 0x75, 0xdd,
	0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xef, 0x9f, 0x93, 0xde, 0x61, 0x01, 0x00, 0x00,
}

func (m *VrfVoteExtension) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VrfVoteExtension) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VrfVoteExtension) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ChainHash) > 0 {
		i -= len(m.ChainHash)
		copy(dAtA[i:], m.ChainHash)
		i = encodeVarintVoteExtension(dAtA, i, uint64(len(m.ChainHash)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PreviousSignature) > 0 {
		i -= len(m.PreviousSignature)
		copy(dAtA[i:], m.PreviousSignature)
		i = encodeVarintVoteExtension(dAtA, i, uint64(len(m.PreviousSignature)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signature) > 0 {
		i -= len(m.Signature)
		copy(dAtA[i:], m.Signature)
		i = encodeVarintVoteExtension(dAtA, i, uint64(len(m.Signature)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Randomness) > 0 {
		i -= len(m.Randomness)
		copy(dAtA[i:], m.Randomness)
		i = encodeVarintVoteExtension(dAtA, i, uint64(len(m.Randomness)))
		i--
		dAtA[i] = 0x12
	}
	if m.DrandRound != 0 {
		i = encodeVarintVoteExtension(dAtA, i, uint64(m.DrandRound))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintVoteExtension(dAtA []byte, offset int, v uint64) int {
	offset -= sovVoteExtension(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VrfVoteExtension) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DrandRound != 0 {
		n += 1 + sovVoteExtension(uint64(m.DrandRound))
	}
	l = len(m.Randomness)
	if l > 0 {
		n += 1 + l + sovVoteExtension(uint64(l))
	}
	l = len(m.Signature)
	if l > 0 {
		n += 1 + l + sovVoteExtension(uint64(l))
	}
	l = len(m.PreviousSignature)
	if l > 0 {
		n += 1 + l + sovVoteExtension(uint64(l))
	}
	l = len(m.ChainHash)
	if l > 0 {
		n += 1 + l + sovVoteExtension(uint64(l))
	}
	return n
}

func sovVoteExtension(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVoteExtension(x uint64) (n int) {
	return sovVoteExtension(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VrfVoteExtension) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVoteExtension
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VrfVoteExtension: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VrfVoteExtension: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DrandRound", wireType)
			}
			m.DrandRound = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DrandRound |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Randomness", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExtension
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExtension
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Randomness = append(m.Randomness[:0], dAtA[iNdEx:postIndex]...)
			if m.Randomness == nil {
				m.Randomness = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExtension
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExtension
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signature = append(m.Signature[:0], dAtA[iNdEx:postIndex]...)
			if m.Signature == nil {
				m.Signature = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousSignature", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExtension
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExtension
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousSignature = append(m.PreviousSignature[:0], dAtA[iNdEx:postIndex]...)
			if m.PreviousSignature == nil {
				m.PreviousSignature = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVoteExtension
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthVoteExtension
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthVoteExtension
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainHash = append(m.ChainHash[:0], dAtA[iNdEx:postIndex]...)
			if m.ChainHash == nil {
				m.ChainHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVoteExtension(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVoteExtension
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVoteExtension(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVoteExtension
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteExtension
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVoteExtension
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVoteExtension
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVoteExtension
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVoteExtension
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVoteExtension        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVoteExtension          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVoteExtension = fmt.Errorf("proto: unexpected end of group")
)
