// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package vrfv1

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_VrfBeacon                    protoreflect.MessageDescriptor
	fd_VrfBeacon_drand_round        protoreflect.FieldDescriptor
	fd_VrfBeacon_randomness         protoreflect.FieldDescriptor
	fd_VrfBeacon_signature          protoreflect.FieldDescriptor
	fd_VrfBeacon_previous_signature protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_vrf_v1_vrf_proto_init()
	md_VrfBeacon = File_vexxvakan_vrf_v1_vrf_proto.Messages().ByName("VrfBeacon")
	fd_VrfBeacon_drand_round = md_VrfBeacon.Fields().ByName("drand_round")
	fd_VrfBeacon_randomness = md_VrfBeacon.Fields().ByName("randomness")
	fd_VrfBeacon_signature = md_VrfBeacon.Fields().ByName("signature")
	fd_VrfBeacon_previous_signature = md_VrfBeacon.Fields().ByName("previous_signature")
}

var _ protoreflect.Message = (*fastReflection_VrfBeacon)(nil)

type fastReflection_VrfBeacon VrfBeacon

func (x *VrfBeacon) ProtoReflect() protoreflect.Message {
	return (*fastReflection_VrfBeacon)(x)
}

func (x *VrfBeacon) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_vrf_v1_vrf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_VrfBeacon_messageType fastReflection_VrfBeacon_messageType
var _ protoreflect.MessageType = fastReflection_VrfBeacon_messageType{}

type fastReflection_VrfBeacon_messageType struct{}

func (x fastReflection_VrfBeacon_messageType) Zero() protoreflect.Message {
	return (*fastReflection_VrfBeacon)(nil)
}
func (x fastReflection_VrfBeacon_messageType) New() protoreflect.Message {
	return new(fastReflection_VrfBeacon)
}
func (x fastReflection_VrfBeacon_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfBeacon
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_VrfBeacon) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfBeacon
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_VrfBeacon) Type() protoreflect.MessageType {
	return _fastReflection_VrfBeacon_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_VrfBeacon) New() protoreflect.Message {
	return new(fastReflection_VrfBeacon)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_VrfBeacon) Interface() protoreflect.ProtoMessage {
	return (*VrfBeacon)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_VrfBeacon) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.DrandRound != uint64(0) {
		value := protoreflect.ValueOfUint64(x.DrandRound)
		if !f(fd_VrfBeacon_drand_round, value) {
			return
		}
	}
	if len(x.Randomness) != 0 {
		value := protoreflect.ValueOfBytes(x.Randomness)
		if !f(fd_VrfBeacon_randomness, value) {
			return
		}
	}
	if len(x.Signature) != 0 {
		value := protoreflect.ValueOfBytes(x.Signature)
		if !f(fd_VrfBeacon_signature, value) {
			return
		}
	}
	if len(x.PreviousSignature) != 0 {
		value := protoreflect.ValueOfBytes(x.PreviousSignature)
		if !f(fd_VrfBeacon_previous_signature, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_VrfBeacon) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfBeacon.drand_round":
		return x.DrandRound != uint64(0)
	case "vexxvakan.vrf.v1.VrfBeacon.randomness":
		return len(x.Randomness) != 0
	case "vexxvakan.vrf.v1.VrfBeacon.signature":
		return len(x.Signature) != 0
	case "vexxvakan.vrf.v1.VrfBeacon.previous_signature":
		return len(x.PreviousSignature) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfBeacon"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfBeacon does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfBeacon) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfBeacon.drand_round":
		x.DrandRound = uint64(0)
	case "vexxvakan.vrf.v1.VrfBeacon.randomness":
		x.Randomness = nil
	case "vexxvakan.vrf.v1.VrfBeacon.signature":
		x.Signature = nil
	case "vexxvakan.vrf.v1.VrfBeacon.previous_signature":
		x.PreviousSignature = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfBeacon"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfBeacon does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_VrfBeacon) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.vrf.v1.VrfBeacon.drand_round":
		value := x.DrandRound
		return protoreflect.ValueOfUint64(value)
	case "vexxvakan.vrf.v1.VrfBeacon.randomness":
		value := x.Randomness
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.v1.VrfBeacon.signature":
		value := x.Signature
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.v1.VrfBeacon.previous_signature":
		value := x.PreviousSignature
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfBeacon"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfBeacon does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfBeacon) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfBeacon.drand_round":
		x.DrandRound = value.Uint()
	case "vexxvakan.vrf.v1.VrfBeacon.randomness":
		x.Randomness = value.Bytes()
	case "vexxvakan.vrf.v1.VrfBeacon.signature":
		x.Signature = value.Bytes()
	case "vexxvakan.vrf.v1.VrfBeacon.previous_signature":
		x.PreviousSignature = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfBeacon"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfBeacon does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfBeacon) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfBeacon.drand_round":
		panic(fmt.Errorf("field drand_round of message vexxvakan.vrf.v1.VrfBeacon is not mutable"))
	case "vexxvakan.vrf.v1.VrfBeacon.randomness":
		panic(fmt.Errorf("field randomness of message vexxvakan.vrf.v1.VrfBeacon is not mutable"))
	case "vexxvakan.vrf.v1.VrfBeacon.signature":
		panic(fmt.Errorf("field signature of message vexxvakan.vrf.v1.VrfBeacon is not mutable"))
	case "vexxvakan.vrf.v1.VrfBeacon.previous_signature":
		panic(fmt.Errorf("field previous_signature of message vexxvakan.vrf.v1.VrfBeacon is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfBeacon"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfBeacon does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_VrfBeacon) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfBeacon.drand_round":
		return protoreflect.ValueOfUint64(uint64(0))
	case "vexxvakan.vrf.v1.VrfBeacon.randomness":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.v1.VrfBeacon.signature":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.v1.VrfBeacon.previous_signature":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfBeacon"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfBeacon does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_VrfBeacon) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.vrf.v1.VrfBeacon", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_VrfBeacon) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfBeacon) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_VrfBeacon) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_VrfBeacon) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*VrfBeacon)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.DrandRound != 0 {
			n += 1 + runtime.Sov(uint64(x.DrandRound))
		}
		l = len(x.Randomness)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Signature)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.PreviousSignature)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*VrfBeacon)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.PreviousSignature) > 0 {
			i -= len(x.PreviousSignature)
			copy(dAtA[i:], x.PreviousSignature)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.PreviousSignature)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.Signature) > 0 {
			i -= len(x.Signature)
			copy(dAtA[i:], x.Signature)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Signature)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.Randomness) > 0 {
			i -= len(x.Randomness)
			copy(dAtA[i:], x.Randomness)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Randomness)))
			i--
			dAtA[i] = 0x12
		}
		if x.DrandRound != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.DrandRound))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*VrfBeacon)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfBeacon: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfBeacon: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DrandRound", wireType)
				}
				x.DrandRound = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.DrandRound |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Randomness", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Randomness = append(x.Randomness[:0], dAtA[iNdEx:postIndex]...)
				if x.Randomness == nil {
					x.Randomness = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Signature", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Signature = append(x.Signature[:0], dAtA[iNdEx:postIndex]...)
				if x.Signature == nil {
					x.Signature = []byte{}
				}
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field PreviousSignature", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.PreviousSignature = append(x.PreviousSignature[:0], dAtA[iNdEx:postIndex]...)
				if x.PreviousSignature == nil {
					x.PreviousSignature = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_AllowlistEntry         protoreflect.MessageDescriptor
	fd_AllowlistEntry_address protoreflect.FieldDescriptor
	fd_AllowlistEntry_label   protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_vrf_v1_vrf_proto_init()
	md_AllowlistEntry = File_vexxvakan_vrf_v1_vrf_proto.Messages().ByName("AllowlistEntry")
	fd_AllowlistEntry_address = md_AllowlistEntry.Fields().ByName("address")
	fd_AllowlistEntry_label = md_AllowlistEntry.Fields().ByName("label")
}

var _ protoreflect.Message = (*fastReflection_AllowlistEntry)(nil)

type fastReflection_AllowlistEntry AllowlistEntry

func (x *AllowlistEntry) ProtoReflect() protoreflect.Message {
	return (*fastReflection_AllowlistEntry)(x)
}

func (x *AllowlistEntry) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_vrf_v1_vrf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_AllowlistEntry_messageType fastReflection_AllowlistEntry_messageType
var _ protoreflect.MessageType = fastReflection_AllowlistEntry_messageType{}

type fastReflection_AllowlistEntry_messageType struct{}

func (x fastReflection_AllowlistEntry_messageType) Zero() protoreflect.Message {
	return (*fastReflection_AllowlistEntry)(nil)
}
func (x fastReflection_AllowlistEntry_messageType) New() protoreflect.Message {
	return new(fastReflection_AllowlistEntry)
}
func (x fastReflection_AllowlistEntry_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_AllowlistEntry
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_AllowlistEntry) Descriptor() protoreflect.MessageDescriptor {
	return md_AllowlistEntry
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_AllowlistEntry) Type() protoreflect.MessageType {
	return _fastReflection_AllowlistEntry_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_AllowlistEntry) New() protoreflect.Message {
	return new(fastReflection_AllowlistEntry)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_AllowlistEntry) Interface() protoreflect.ProtoMessage {
	return (*AllowlistEntry)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_AllowlistEntry) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Address != "" {
		value := protoreflect.ValueOfString(x.Address)
		if !f(fd_AllowlistEntry_address, value) {
			return
		}
	}
	if x.Label != "" {
		value := protoreflect.ValueOfString(x.Label)
		if !f(fd_AllowlistEntry_label, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_AllowlistEntry) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.AllowlistEntry.address":
		return x.Address != ""
	case "vexxvakan.vrf.v1.AllowlistEntry.label":
		return x.Label != ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.AllowlistEntry"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.AllowlistEntry does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AllowlistEntry) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.AllowlistEntry.address":
		x.Address = ""
	case "vexxvakan.vrf.v1.AllowlistEntry.label":
		x.Label = ""
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.AllowlistEntry"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.AllowlistEntry does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_AllowlistEntry) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.vrf.v1.AllowlistEntry.address":
		value := x.Address
		return protoreflect.ValueOfString(value)
	case "vexxvakan.vrf.v1.AllowlistEntry.label":
		value := x.Label
		return protoreflect.ValueOfString(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.AllowlistEntry"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.AllowlistEntry does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AllowlistEntry) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.AllowlistEntry.address":
		x.Address = value.Interface().(string)
	case "vexxvakan.vrf.v1.AllowlistEntry.label":
		x.Label = value.Interface().(string)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.AllowlistEntry"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.AllowlistEntry does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AllowlistEntry) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.AllowlistEntry.address":
		panic(fmt.Errorf("field address of message vexxvakan.vrf.v1.AllowlistEntry is not mutable"))
	case "vexxvakan.vrf.v1.AllowlistEntry.label":
		panic(fmt.Errorf("field label of message vexxvakan.vrf.v1.AllowlistEntry is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.AllowlistEntry"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.AllowlistEntry does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_AllowlistEntry) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.AllowlistEntry.address":
		return protoreflect.ValueOfString("")
	case "vexxvakan.vrf.v1.AllowlistEntry.label":
		return protoreflect.ValueOfString("")
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.AllowlistEntry"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.AllowlistEntry does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_AllowlistEntry) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.vrf.v1.AllowlistEntry", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_AllowlistEntry) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_AllowlistEntry) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_AllowlistEntry) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_AllowlistEntry) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*AllowlistEntry)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Address)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Label)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*AllowlistEntry)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Label) > 0 {
			i -= len(x.Label)
			copy(dAtA[i:], x.Label)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Label)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Address) > 0 {
			i -= len(x.Address)
			copy(dAtA[i:], x.Address)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Address)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*AllowlistEntry)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AllowlistEntry: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: AllowlistEntry: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Address = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Label", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Label = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_VrfIdentity                      protoreflect.MessageDescriptor
	fd_VrfIdentity_validator_address    protoreflect.FieldDescriptor
	fd_VrfIdentity_drand_bls_public_key protoreflect.FieldDescriptor
	fd_VrfIdentity_chain_hash           protoreflect.FieldDescriptor
	fd_VrfIdentity_signal_unix_sec      protoreflect.FieldDescriptor
	fd_VrfIdentity_signal_reshare_epoch protoreflect.FieldDescriptor
)

func init() {
	file_vexxvakan_vrf_v1_vrf_proto_init()
	md_VrfIdentity = File_vexxvakan_vrf_v1_vrf_proto.Messages().ByName("VrfIdentity")
	fd_VrfIdentity_validator_address = md_VrfIdentity.Fields().ByName("validator_address")
	fd_VrfIdentity_drand_bls_public_key = md_VrfIdentity.Fields().ByName("drand_bls_public_key")
	fd_VrfIdentity_chain_hash = md_VrfIdentity.Fields().ByName("chain_hash")
	fd_VrfIdentity_signal_unix_sec = md_VrfIdentity.Fields().ByName("signal_unix_sec")
	fd_VrfIdentity_signal_reshare_epoch = md_VrfIdentity.Fields().ByName("signal_reshare_epoch")
}

var _ protoreflect.Message = (*fastReflection_VrfIdentity)(nil)

type fastReflection_VrfIdentity VrfIdentity

func (x *VrfIdentity) ProtoReflect() protoreflect.Message {
	return (*fastReflection_VrfIdentity)(x)
}

func (x *VrfIdentity) slowProtoReflect() protoreflect.Message {
	mi := &file_vexxvakan_vrf_v1_vrf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_VrfIdentity_messageType fastReflection_VrfIdentity_messageType
var _ protoreflect.MessageType = fastReflection_VrfIdentity_messageType{}

type fastReflection_VrfIdentity_messageType struct{}

func (x fastReflection_VrfIdentity_messageType) Zero() protoreflect.Message {
	return (*fastReflection_VrfIdentity)(nil)
}
func (x fastReflection_VrfIdentity_messageType) New() protoreflect.Message {
	return new(fastReflection_VrfIdentity)
}
func (x fastReflection_VrfIdentity_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfIdentity
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_VrfIdentity) Descriptor() protoreflect.MessageDescriptor {
	return md_VrfIdentity
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_VrfIdentity) Type() protoreflect.MessageType {
	return _fastReflection_VrfIdentity_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_VrfIdentity) New() protoreflect.Message {
	return new(fastReflection_VrfIdentity)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_VrfIdentity) Interface() protoreflect.ProtoMessage {
	return (*VrfIdentity)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_VrfIdentity) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.ValidatorAddress != "" {
		value := protoreflect.ValueOfString(x.ValidatorAddress)
		if !f(fd_VrfIdentity_validator_address, value) {
			return
		}
	}
	if len(x.DrandBlsPublicKey) != 0 {
		value := protoreflect.ValueOfBytes(x.DrandBlsPublicKey)
		if !f(fd_VrfIdentity_drand_bls_public_key, value) {
			return
		}
	}
	if len(x.ChainHash) != 0 {
		value := protoreflect.ValueOfBytes(x.ChainHash)
		if !f(fd_VrfIdentity_chain_hash, value) {
			return
		}
	}
	if x.SignalUnixSec != int64(0) {
		value := protoreflect.ValueOfInt64(x.SignalUnixSec)
		if !f(fd_VrfIdentity_signal_unix_sec, value) {
			return
		}
	}
	if x.SignalReshareEpoch != uint64(0) {
		value := protoreflect.ValueOfUint64(x.SignalReshareEpoch)
		if !f(fd_VrfIdentity_signal_reshare_epoch, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_VrfIdentity) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfIdentity.validator_address":
		return x.ValidatorAddress != ""
	case "vexxvakan.vrf.v1.VrfIdentity.drand_bls_public_key":
		return len(x.DrandBlsPublicKey) != 0
	case "vexxvakan.vrf.v1.VrfIdentity.chain_hash":
		return len(x.ChainHash) != 0
	case "vexxvakan.vrf.v1.VrfIdentity.signal_unix_sec":
		return x.SignalUnixSec != int64(0)
	case "vexxvakan.vrf.v1.VrfIdentity.signal_reshare_epoch":
		return x.SignalReshareEpoch != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfIdentity"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfIdentity does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfIdentity) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfIdentity.validator_address":
		x.ValidatorAddress = ""
	case "vexxvakan.vrf.v1.VrfIdentity.drand_bls_public_key":
		x.DrandBlsPublicKey = nil
	case "vexxvakan.vrf.v1.VrfIdentity.chain_hash":
		x.ChainHash = nil
	case "vexxvakan.vrf.v1.VrfIdentity.signal_unix_sec":
		x.SignalUnixSec = int64(0)
	case "vexxvakan.vrf.v1.VrfIdentity.signal_reshare_epoch":
		x.SignalReshareEpoch = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfIdentity"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfIdentity does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_VrfIdentity) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "vexxvakan.vrf.v1.VrfIdentity.validator_address":
		value := x.ValidatorAddress
		return protoreflect.ValueOfString(value)
	case "vexxvakan.vrf.v1.VrfIdentity.drand_bls_public_key":
		value := x.DrandBlsPublicKey
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.v1.VrfIdentity.chain_hash":
		value := x.ChainHash
		return protoreflect.ValueOfBytes(value)
	case "vexxvakan.vrf.v1.VrfIdentity.signal_unix_sec":
		value := x.SignalUnixSec
		return protoreflect.ValueOfInt64(value)
	case "vexxvakan.vrf.v1.VrfIdentity.signal_reshare_epoch":
		value := x.SignalReshareEpoch
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfIdentity"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfIdentity does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfIdentity) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfIdentity.validator_address":
		x.ValidatorAddress = value.Interface().(string)
	case "vexxvakan.vrf.v1.VrfIdentity.drand_bls_public_key":
		x.DrandBlsPublicKey = value.Bytes()
	case "vexxvakan.vrf.v1.VrfIdentity.chain_hash":
		x.ChainHash = value.Bytes()
	case "vexxvakan.vrf.v1.VrfIdentity.signal_unix_sec":
		x.SignalUnixSec = value.Int()
	case "vexxvakan.vrf.v1.VrfIdentity.signal_reshare_epoch":
		x.SignalReshareEpoch = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfIdentity"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfIdentity does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfIdentity) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfIdentity.validator_address":
		panic(fmt.Errorf("field validator_address of message vexxvakan.vrf.v1.VrfIdentity is not mutable"))
	case "vexxvakan.vrf.v1.VrfIdentity.drand_bls_public_key":
		panic(fmt.Errorf("field drand_bls_public_key of message vexxvakan.vrf.v1.VrfIdentity is not mutable"))
	case "vexxvakan.vrf.v1.VrfIdentity.chain_hash":
		panic(fmt.Errorf("field chain_hash of message vexxvakan.vrf.v1.VrfIdentity is not mutable"))
	case "vexxvakan.vrf.v1.VrfIdentity.signal_unix_sec":
		panic(fmt.Errorf("field signal_unix_sec of message vexxvakan.vrf.v1.VrfIdentity is not mutable"))
	case "vexxvakan.vrf.v1.VrfIdentity.signal_reshare_epoch":
		panic(fmt.Errorf("field signal_reshare_epoch of message vexxvakan.vrf.v1.VrfIdentity is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfIdentity"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfIdentity does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_VrfIdentity) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "vexxvakan.vrf.v1.VrfIdentity.validator_address":
		return protoreflect.ValueOfString("")
	case "vexxvakan.vrf.v1.VrfIdentity.drand_bls_public_key":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.v1.VrfIdentity.chain_hash":
		return protoreflect.ValueOfBytes(nil)
	case "vexxvakan.vrf.v1.VrfIdentity.signal_unix_sec":
		return protoreflect.ValueOfInt64(int64(0))
	case "vexxvakan.vrf.v1.VrfIdentity.signal_reshare_epoch":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: vexxvakan.vrf.v1.VrfIdentity"))
		}
		panic(fmt.Errorf("message vexxvakan.vrf.v1.VrfIdentity does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_VrfIdentity) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in vexxvakan.vrf.v1.VrfIdentity", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_VrfIdentity) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_VrfIdentity) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_VrfIdentity) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_VrfIdentity) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*VrfIdentity)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.ValidatorAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DrandBlsPublicKey)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ChainHash)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.SignalUnixSec != 0 {
			n += 1 + runtime.Sov(uint64(x.SignalUnixSec))
		}
		if x.SignalReshareEpoch != 0 {
			n += 1 + runtime.Sov(uint64(x.SignalReshareEpoch))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*VrfIdentity)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.SignalReshareEpoch != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SignalReshareEpoch))
			i--
			dAtA[i] = 0x28
		}
		if x.SignalUnixSec != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SignalUnixSec))
			i--
			dAtA[i] = 0x20
		}
		if len(x.ChainHash) > 0 {
			i -= len(x.ChainHash)
			copy(dAtA[i:], x.ChainHash)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ChainHash)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.DrandBlsPublicKey) > 0 {
			i -= len(x.DrandBlsPublicKey)
			copy(dAtA[i:], x.DrandBlsPublicKey)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DrandBlsPublicKey)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.ValidatorAddress) > 0 {
			i -= len(x.ValidatorAddress)
			copy(dAtA[i:], x.ValidatorAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ValidatorAddress)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*VrfIdentity)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfIdentity: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: VrfIdentity: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ValidatorAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DrandBlsPublicKey", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DrandBlsPublicKey = append(x.DrandBlsPublicKey[:0], dAtA[iNdEx:postIndex]...)
				if x.DrandBlsPublicKey == nil {
					x.DrandBlsPublicKey = []byte{}
				}
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ChainHash", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ChainHash = append(x.ChainHash[:0], dAtA[iNdEx:postIndex]...)
				if x.ChainHash == nil {
					x.ChainHash = []byte{}
				}
				iNdEx = postIndex
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SignalUnixSec", wireType)
				}
				x.SignalUnixSec = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SignalUnixSec |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SignalReshareEpoch", wireType)
				}
				x.SignalReshareEpoch = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SignalReshareEpoch |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: vexxvakan/vrf/v1/vrf.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VrfBeacon is the canonical drand beacon selected for a given block height.
// It carries only the fields required for full on-chain verification.
type VrfBeacon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// drand_round is the drand round number.
	DrandRound uint64 `protobuf:"varint,1,opt,name=drand_round,json=drandRound,proto3" json:"drand_round,omitempty"`
	// randomness is SHA256(signature).
	Randomness []byte `protobuf:"bytes,2,opt,name=randomness,proto3" json:"randomness,omitempty"`
	// signature is the drand BLS signature for this round.
	Signature []byte `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// previous_signature is the BLS signature of the previous round, required
	// for chained-scheme verification.
	PreviousSignature []byte `protobuf:"bytes,4,opt,name=previous_signature,json=previousSignature,proto3" json:"previous_signature,omitempty"`
}

func (x *VrfBeacon) Reset() {
	*x = VrfBeacon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_vrf_v1_vrf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfBeacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfBeacon) ProtoMessage() {}

// Deprecated: Use VrfBeacon.ProtoReflect.Descriptor instead.
func (*VrfBeacon) Descriptor() ([]byte, []int) {
	return file_vexxvakan_vrf_v1_vrf_proto_rawDescGZIP(), []int{0}
}

func (x *VrfBeacon) GetDrandRound() uint64 {
	if x != nil {
		return x.DrandRound
	}
	return 0
}

func (x *VrfBeacon) GetRandomness() []byte {
	if x != nil {
		return x.Randomness
	}
	return nil
}

func (x *VrfBeacon) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *VrfBeacon) GetPreviousSignature() []byte {
	if x != nil {
		return x.PreviousSignature
	}
	return nil
}

// AllowlistEntry maps an address to a human-readable label for auditing.
type AllowlistEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// address is the allowlisted account address.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// label is free-form metadata for operator UX / auditing.
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *AllowlistEntry) Reset() {
	*x = AllowlistEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_vrf_v1_vrf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllowlistEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowlistEntry) ProtoMessage() {}

// Deprecated: Use AllowlistEntry.ProtoReflect.Descriptor instead.
func (*AllowlistEntry) Descriptor() ([]byte, []int) {
	return file_vexxvakan_vrf_v1_vrf_proto_rawDescGZIP(), []int{1}
}

func (x *AllowlistEntry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AllowlistEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// VrfIdentity binds a validator to a drand BLS identity / share for monitoring
// and resharing coordination.
type VrfIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// validator_address is the validator operator address.
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validator_address,json=validatorAddress,proto3" json:"validator_address,omitempty"`
	// drand_bls_public_key is the validator's drand BLS public key/share.
	DrandBlsPublicKey []byte `protobuf:"bytes,2,opt,name=drand_bls_public_key,json=drandBlsPublicKey,proto3" json:"drand_bls_public_key,omitempty"`
	// chain_hash is the drand chain hash this identity is bound to.
	ChainHash []byte `protobuf:"bytes,3,opt,name=chain_hash,json=chainHash,proto3" json:"chain_hash,omitempty"`
	// signal_unix_sec is the UNIX time when this identity was first registered.
	SignalUnixSec int64 `protobuf:"varint,4,opt,name=signal_unix_sec,json=signalUnixSec,proto3" json:"signal_unix_sec,omitempty"`
	// signal_reshare_epoch is the value of VrfParams.reshare_epoch when this
	// identity was first registered.
	SignalReshareEpoch uint64 `protobuf:"varint,5,opt,name=signal_reshare_epoch,json=signalReshareEpoch,proto3" json:"signal_reshare_epoch,omitempty"`
}

func (x *VrfIdentity) Reset() {
	*x = VrfIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vexxvakan_vrf_v1_vrf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VrfIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VrfIdentity) ProtoMessage() {}

// Deprecated: Use VrfIdentity.ProtoReflect.Descriptor instead.
func (*VrfIdentity) Descriptor() ([]byte, []int) {
	return file_vexxvakan_vrf_v1_vrf_proto_rawDescGZIP(), []int{2}
}

func (x *VrfIdentity) GetValidatorAddress() string {
	if x != nil {
		return x.ValidatorAddress
	}
	return ""
}

func (x *VrfIdentity) GetDrandBlsPublicKey() []byte {
	if x != nil {
		return x.DrandBlsPublicKey
	}
	return nil
}

func (x *VrfIdentity) GetChainHash() []byte {
	if x != nil {
		return x.ChainHash
	}
	return nil
}

func (x *VrfIdentity) GetSignalUnixSec() int64 {
	if x != nil {
		return x.SignalUnixSec
	}
	return 0
}

func (x *VrfIdentity) GetSignalReshareEpoch() uint64 {
	if x != nil {
		return x.SignalReshareEpoch
	}
	return 0
}

var File_vexxvakan_vrf_v1_vrf_proto protoreflect.FileDescriptor

var file_vexxvakan_vrf_v1_vrf_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x76, 0x72, 0x66, 0x2f,
	0x76, 0x31, 0x2f, 0x76, 0x72, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x76, 0x65,
	0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e, 0x76, 0x31, 0x1a, 0x19,
	0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73,
	0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9f, 0x01, 0x0a, 0x09, 0x56, 0x72, 0x66, 0x42, 0x65, 0x61, 0x63, 0x6f, 0x6e, 0x12, 0x1f, 0x0a,
	0x0b, 0x64, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0a, 0x64, 0x72, 0x61, 0x6e, 0x64, 0x52, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x2d, 0x0a, 0x12,
	0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x11, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f,
	0x75, 0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x3a, 0x04, 0xe8, 0xa0, 0x1f,
	0x01, 0x22, 0x60, 0x0a, 0x0e, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x6c, 0x69, 0x73, 0x74, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x32, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x42, 0x18, 0xd2, 0xb4, 0x2d, 0x14, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x3a, 0x04, 0xe8,
	0xa0, 0x1f, 0x01, 0x22, 0x8d, 0x02, 0x0a, 0x0b, 0x56, 0x72, 0x66, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x12, 0x4e, 0x0a, 0x11, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x21,
	0xd2, 0xb4, 0x2d, 0x1d, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x74, 0x72, 0x69, 0x6e,
	0x67, 0x52, 0x10, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x2f, 0x0a, 0x14, 0x64, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x62, 0x6c, 0x73,
	0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x11, 0x64, 0x72, 0x61, 0x6e, 0x64, 0x42, 0x6c, 0x73, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e,
	0x69, 0x78, 0x5f, 0x73, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x55, 0x6e, 0x69, 0x78, 0x53, 0x65, 0x63, 0x12, 0x30, 0x0a, 0x14, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f, 0x65, 0x70,
	0x6f, 0x63, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x12, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x52, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x45, 0x70, 0x6f, 0x63, 0x68, 0x3a, 0x04, 0xe8,
	0xa0, 0x1f, 0x01, 0x42, 0xab, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x76, 0x65, 0x78, 0x78,
	0x76, 0x61, 0x6b, 0x61, 0x6e, 0x2e, 0x76, 0x72, 0x66, 0x2e, 0x76, 0x31, 0x42, 0x08, 0x56, 0x72,
	0x66, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x65, 0x78, 0x78, 0x76,
	0x61, 0x6b, 0x61, 0x6e, 0x2f, 0x76, 0x72, 0x66, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x72, 0x66, 0x76,
	0x31, 0xa2, 0x02, 0x03, 0x56, 0x56, 0x58, 0xaa, 0x02, 0x10, 0x56, 0x65, 0x78, 0x78, 0x76, 0x61,
	0x6b, 0x61, 0x6e, 0x2e, 0x56, 0x72, 0x66, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x10, 0x56, 0x65, 0x78,
	0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x5c, 0x56, 0x72, 0x66, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c,
	0x56, 0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x5c, 0x56, 0x72, 0x66, 0x5c, 0x56, 0x31,
	0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x56,
	0x65, 0x78, 0x78, 0x76, 0x61, 0x6b, 0x61, 0x6e, 0x3a, 0x3a, 0x56, 0x72, 0x66, 0x3a, 0x3a, 0x56,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vexxvakan_vrf_v1_vrf_proto_rawDescOnce sync.Once
	file_vexxvakan_vrf_v1_vrf_proto_rawDescData = file_vexxvakan_vrf_v1_vrf_proto_rawDesc
)

func file_vexxvakan_vrf_v1_vrf_proto_rawDescGZIP() []byte {
	file_vexxvakan_vrf_v1_vrf_proto_rawDescOnce.Do(func() {
		file_vexxvakan_vrf_v1_vrf_proto_rawDescData = protoimpl.X.CompressGZIP(file_vexxvakan_vrf_v1_vrf_proto_rawDescData)
	})
	return file_vexxvakan_vrf_v1_vrf_proto_rawDescData
}

var file_vexxvakan_vrf_v1_vrf_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vexxvakan_vrf_v1_vrf_proto_goTypes = []interface{}{
	(*VrfBeacon)(nil),      // 0: vexxvakan.vrf.v1.VrfBeacon
	(*AllowlistEntry)(nil), // 1: vexxvakan.vrf.v1.AllowlistEntry
	(*VrfIdentity)(nil),    // 2: vexxvakan.vrf.v1.VrfIdentity
}
var file_vexxvakan_vrf_v1_vrf_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vexxvakan_vrf_v1_vrf_proto_init() }
func file_vexxvakan_vrf_v1_vrf_proto_init() {
	if File_vexxvakan_vrf_v1_vrf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vexxvakan_vrf_v1_vrf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfBeacon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vexxvakan_vrf_v1_vrf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllowlistEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vexxvakan_vrf_v1_vrf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VrfIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vexxvakan_vrf_v1_vrf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vexxvakan_vrf_v1_vrf_proto_goTypes,
		DependencyIndexes: file_vexxvakan_vrf_v1_vrf_proto_depIdxs,
		MessageInfos:      file_vexxvakan_vrf_v1_vrf_proto_msgTypes,
	}.Build()
	File_vexxvakan_vrf_v1_vrf_proto = out.File
	file_vexxvakan_vrf_v1_vrf_proto_rawDesc = nil
	file_vexxvakan_vrf_v1_vrf_proto_goTypes = nil
	file_vexxvakan_vrf_v1_vrf_proto_depIdxs = nil
}
